#Requires -Version 5.1
[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$SourceRoot,[Parameter(Mandatory=$true)][string]$PackageRoot)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
$Utf8=New-Object Text.UTF8Encoding($false)
$ExpectedFormal='f1520907d54e406e7d82f591e3799f07f569218aff0c321ac3b836b6c649da10'
function Fail([string]$m){throw $m}
function Get-Hash([string]$p){return (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function TH([string]$s){$a=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($a.ComputeHash($Utf8.GetBytes($s))).Replace('-','').ToLowerInvariant())}finally{$a.Dispose()}}
function C([string]$r,[string]$p,[bool]$e=$true){$rf=[IO.Path]::GetFullPath($r).TrimEnd('\');$f=[IO.Path]::GetFullPath((Join-Path $rf ($p.Replace('/','\'))));if(-not$f.StartsWith($rf+'\',[StringComparison]::OrdinalIgnoreCase)){Fail "escape:$p"};if($e-and-not(Test-Path -LiteralPath $f -PathType Leaf)){Fail "missing:$f"};return $f}
function A([string]$r,[object[]]$m){$x=foreach($e in($m|Sort-Object relative_path)){[string]$e.relative_path+'|'+(Get-Hash (C $r ([string]$e.relative_path)))};return TH ($x-join[char]10)}
function Run([string]$id,[scriptblock]$action,[string]$pattern){$old=$ErrorActionPreference;$ErrorActionPreference='Continue';$o=@(&$action 2>&1);$code=$LASTEXITCODE;$ErrorActionPreference=$old;$txt=$o-join"`n";[IO.File]::WriteAllLines((Join-Path $PackageRoot ('logs\negative-'+$id+'.txt')),@($o|ForEach-Object{[string]$_}),$Utf8);return [pscustomobject][ordered]@{gate_id=$id;status=if($code-ne0-and$txt-match$pattern){'passed'}else{'failed'};exit_code=$code;expected_pattern=$pattern;pattern_match=[bool]($txt-match$pattern);formal_aggregate_after='';formal_targets_absent='';notes=($txt-split"`n"|Select-Object -First 1)}}
$SourceRoot=(Resolve-Path -LiteralPath $SourceRoot).Path.TrimEnd('\');$PackageRoot=(Resolve-Path -LiteralPath $PackageRoot).Path.TrimEnd('\');$manifest=@(Import-Csv -LiteralPath (Join-Path $PackageRoot 'formal-32-baseline.csv') -Encoding UTF8);$newFiles=@(Import-Csv -LiteralPath (Join-Path $PackageRoot 'new-file-targets.csv') -Encoding UTF8);$executor=Join-Path $PackageRoot 'scripts\Invoke-Ascend950FormalTransaction.ps1';$preflight=Join-Path $PackageRoot 'scripts\Test-Ascend950FormalTransactionPreflight.ps1';$template=Join-Path $PackageRoot 'transaction-review-signoff-template.csv';$templateSha=Get-Hash $template;$before=A $SourceRoot $manifest;if($before-cne$ExpectedFormal){Fail 'formal baseline changed before negative gates'}
$rows=[Collections.Generic.List[object]]::new();$rows.Add((Run 'default-deny' {&'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoProfile -ExecutionPolicy Bypass -File $executor -SourceRoot $SourceRoot -TargetRoot $SourceRoot} 'denied by default'))
$rows.Add((Run 'wrong-token' {&'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoProfile -ExecutionPolicy Bypass -File $executor -SourceRoot $SourceRoot -TargetRoot $SourceRoot -AllowFormalRoot -FormalAuthorizationToken 'WRONG' -BackupRoot (Join-Path $PackageRoot 'rehearsal\fake-backup') -TransactionReviewSignoffPath $template -AuthorizationSignoffSha256 $templateSha} 'authorization token differs'))
$rows.Add((Run 'pending-independent-signoff' {&'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoProfile -ExecutionPolicy Bypass -File $executor -SourceRoot $SourceRoot -TargetRoot $SourceRoot -AllowFormalRoot -FormalAuthorizationToken 'ASCEND950-FORMAL-MERGE-20260813-0F59AA2F-F1520907' -BackupRoot (Join-Path $PackageRoot 'rehearsal\fake-backup') -TransactionReviewSignoffPath $template -AuthorizationSignoffSha256 $templateSha} 'reviewer identity differs'))
foreach($spec in @([pscustomobject]@{id='wrong-mirror-marker';mode='executor'},[pscustomobject]@{id='preexisting-target';mode='preflight'},[pscustomobject]@{id='wrong-premerge-hash';mode='preflight_hash'})){$mirror=Join-Path $PackageRoot ('rehearsal\negative-'+$spec.id);$result=Join-Path $PackageRoot ('rehearsal\negative-result-'+$spec.id);foreach($x in @($mirror,$result)){if(Test-Path -LiteralPath $x){Remove-Item -LiteralPath $x -Recurse -Force};[IO.Directory]::CreateDirectory($x)|Out-Null};foreach($e in $manifest){$s=C $SourceRoot ([string]$e.relative_path);$d=C $mirror ([string]$e.relative_path) $false;[IO.Directory]::CreateDirectory((Split-Path -Parent $d))|Out-Null;[IO.File]::Copy($s,$d,$false)};if($spec.mode-ceq'executor'){[IO.File]::WriteAllText((Join-Path $mirror '.ascend950-formal-transaction-mirror'),'WRONG',$Utf8);$row=Run $spec.id {&'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoProfile -ExecutionPolicy Bypass -File $executor -SourceRoot $SourceRoot -TargetRoot $mirror -ResultRoot $result} 'marker content differs'}elseif($spec.mode-ceq'preflight'){$item=$newFiles[0];$s=C $SourceRoot ([string]$item.source_path);$d=C $mirror ([string]$item.target_path) $false;[IO.Directory]::CreateDirectory((Split-Path -Parent $d))|Out-Null;[IO.File]::Copy($s,$d,$false);$row=Run $spec.id {&'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoProfile -ExecutionPolicy Bypass -File $preflight -SourceRoot $SourceRoot -TargetRoot $mirror -WorkRoot $PackageRoot} 'New-file target already exists'}else{$factsEntry=@($manifest | Where-Object { [IO.Path]::GetFileName([string]$_.relative_path) -ceq 'facts.csv' });if($factsEntry.Count-ne1){Fail 'facts.csv manifest entry count differs'};$f=C $mirror ([string]$factsEntry[0].relative_path);[IO.File]::AppendAllText($f,"`r`n",$Utf8);$row=Run $spec.id {&'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' -NoProfile -ExecutionPolicy Bypass -File $preflight -SourceRoot $SourceRoot -TargetRoot $mirror -WorkRoot $PackageRoot} 'TargetRoot formal aggregate differs'};$rows.Add($row);Remove-Item -LiteralPath $mirror -Recurse -Force;Remove-Item -LiteralPath $result -Recurse -Force}
$after=A $SourceRoot $manifest;$absent=$true;foreach($item in $newFiles){if(Test-Path -LiteralPath (C $SourceRoot ([string]$item.target_path) $false)){$absent=$false}};foreach($r in $rows){$r.formal_aggregate_after=$after;$r.formal_targets_absent=[string]$absent};if ($after -cne $before -or -not $absent -or @($rows | Where-Object { $_.status -cne 'passed' }).Count -ne 0) { Fail 'negative gate suite failed' };[IO.File]::WriteAllLines((Join-Path $PackageRoot 'negative-gates.csv'),($rows|ConvertTo-Csv -NoTypeInformation),$Utf8);$summary=[ordered]@{status='passed';gates=$rows.Count;formal_aggregate_before=$before;formal_aggregate_after=$after;formal_targets_absent=$absent;formal_writes_performed=0};[IO.File]::WriteAllText((Join-Path $PackageRoot 'negative-gates-summary.json'),(($summary|ConvertTo-Json)+"`r`n"),$Utf8);Write-Output($summary|ConvertTo-Json -Compress)
