#Requires -Version 5.1
[CmdletBinding()]
param(
 [string]$RootPath='.',
 [string]$CandidatePath='审计/子代理交接/field_subject_contract_remediation',
 [string]$BaselineManifestPath='',
 [string]$IndependentReviewPath=''
)
$ErrorActionPreference='Stop'
$script:Errors=[Collections.Generic.List[string]]::new()
$script:Warnings=[Collections.Generic.List[string]]::new()
$script:Checks=0
function Err([string]$m){$script:Errors.Add($m)}
function Warn([string]$m){$script:Warnings.Add($m)}
function Check([bool]$ok,[string]$m){$script:Checks++;if( -not $ok){Err $m}}
function Blank($v){return [string]::IsNullOrWhiteSpace([string]$v)}
function Full([string]$root,[string]$p){if([IO.Path]::IsPathRooted($p)){return [IO.Path]::GetFullPath($p)};return [IO.Path]::GetFullPath((Join-Path $root $p.Replace('/',[IO.Path]::DirectorySeparatorChar)))}
function Hash([string]$p){return (Get-FileHash -LiteralPath $p -Algorithm SHA256).Hash.ToLowerInvariant()}
function Profile([string]$p){$b=[IO.File]::ReadAllBytes($p);$bom=$b.Length -ge 3 -and $b[0] -eq 239 -and $b[1] -eq 187 -and $b[2] -eq 191;$utf8=[Text.UTF8Encoding]::new($false,$true);try{$offset=if($bom){3}else{0};$t=$utf8.GetString($b,$offset,$b.Length-$offset);$valid=$true}catch{$t='';$valid=$false};return [pscustomobject]@{valid=$valid;bom=$bom;crlf=([regex]::Matches($t,"`r`n").Count);bare_lf=([regex]::Matches($t,"(?<!`r)`n").Count);bare_cr=([regex]::Matches($t,"`r(?!`n)").Count);final=$(if($b.Length){$b[-1] -in @(10,13)}else{$false});bytes=$b.Length}}
$Kinds=@('object','component','link','object_relation','precision_path','capability','topology')
$Col=[ordered]@{object='object_id';component='component_id';link='link_id';object_relation='object_relation_id';precision_path='precision_path_id';capability='capability_id';topology='topology_id'}
function Kind($r){$x=@($Col.GetEnumerator()|Where-Object{ -not (Blank $r.($_.Value))});if($x.Count -ne 1){return ''};return [string]$x[0].Key}
function ReqFp($r,[string]$newKind='',[string]$newId='',[string]$newField=''){$old=Kind $r;$v=[Collections.Generic.List[string]]::new();[void]$v.Add([string]$r.requirement_id);foreach($k in $Kinds){if( -not (Blank $newKind) -and $k -eq $newKind){[void]$v.Add($newId)}elseif( -not (Blank $newKind) -and $k -eq $old){[void]$v.Add('')}else{[void]$v.Add([string]$r.($Col[$k]))}};if(Blank $newField){[void]$v.Add([string]$r.field_id)}else{[void]$v.Add($newField)};return $v-join'|'}
function Vec($r,[string]$newKind='',[string]$newId=''){$old=Kind $r;$v=foreach($k in $Kinds){if( -not (Blank $newKind) -and $k -eq $newKind){$newId}elseif( -not (Blank $newKind) -and $k -eq $old){''}else{[string]$r.($Col[$k])}};return $v-join[char]31}
function Contract([string]$v,[string]$ctx){$ok=$true;if(Blank $v){Err "empty contract: $ctx";return};$p=@($v.Split(';')|ForEach-Object{$_.Trim()});if(@($p|Where-Object{Blank $_}).Count){Err "empty contract token: $ctx";$ok=$false};if(@($p|Sort-Object -Unique).Count -ne $p.Count){Err "duplicate contract kind: $ctx";$ok=$false};if(@($p|Where-Object{$_ -notin $Kinds}).Count){Err "unknown contract kind: $ctx";$ok=$false};$canon=@($Kinds|Where-Object{$_ -in $p})-join';';if(($p-join';') -cne $canon){Err "noncanonical contract: $ctx; expected=$canon";$ok=$false};$script:Checks+=4}
try{$root=(Resolve-Path -LiteralPath $RootPath).Path}catch{Write-Output "FAIL: root missing: $RootPath";exit 1}
if(Blank $BaselineManifestPath){$BaselineManifestPath=Join-Path $PSScriptRoot 'baseline-manifest.csv'}
$mf=Full $root $BaselineManifestPath;$cand=Full $root $CandidatePath
Check (Test-Path -LiteralPath $mf -PathType Leaf) "baseline manifest missing: $mf"
Check (Test-Path -LiteralPath $cand -PathType Container) "candidate directory missing: $cand"
if($script:Errors.Count){Write-Output "FAIL: $($script:Errors.Count) preflight errors";exit 1}
$manifest=@(Import-Csv -LiteralPath $mf);Check ($manifest.Count -eq 17) "manifest rows expected 17, got $($manifest.Count)";Check (@($manifest|Where-Object role -eq 'required_backup_write').Count -eq 4) 'manifest must name four writable backup files';Check (@($manifest|Group-Object path|Where-Object Count -ne 1).Count -eq 0) 'manifest paths not unique'
$start=@{}
foreach($e in $manifest){$p=Full $root $e.path;Check (Test-Path -LiteralPath $p -PathType Leaf) "baseline file missing: $($e.path)";if( -not (Test-Path -LiteralPath $p)){continue};$h=Hash $p;$start[$e.path]=$h;$q=Profile $p;Check ($h -ceq $e.sha256.ToLowerInvariant()) "baseline hash drift: $($e.path)";Check ($q.bytes -eq [long]$e.bytes) "baseline byte drift: $($e.path)";Check ($q.valid) "invalid UTF-8: $($e.path)";Check ($q.bom.ToString().ToLowerInvariant() -ceq $e.utf8_bom) "BOM drift: $($e.path)";Check ($q.crlf -eq [int]$e.crlf -and $q.bare_lf -eq [int]$e.bare_lf -and $q.bare_cr -eq [int]$e.bare_cr) "newline profile drift: $($e.path)";Check ($q.final.ToString().ToLowerInvariant() -ceq $e.final_newline) "final newline drift: $($e.path)"}
$need=@('README.md','adjudication.csv','field-contract-proposals.csv','row-overlay-proposals.csv','validation-summary.json','Validate-ResearchData.ps1','candidate-schema-columns.csv','candidate-fields.csv','candidate-field-requirements.csv','formal-migration-manifest.csv','formal-file-hashes.csv','candidate-csv-format-audit.csv','verification-summary.json');$candStart=@{}
foreach($n in $need){$p=Join-Path $cand $n;Check (Test-Path -LiteralPath $p -PathType Leaf) "candidate file missing: $n";if(Test-Path -LiteralPath $p){$candStart[$n]=Hash $p}}$schema=@(Import-Csv -LiteralPath (Full $root '数据/schema-columns.csv'));$fields=@(Import-Csv -LiteralPath (Full $root '数据/fields.csv'));$req=@(Import-Csv -LiteralPath (Full $root '数据/field-requirements.csv'));$facts=@(Import-Csv -LiteralPath (Full $root '数据/facts.csv'))
Check ($schema.Count -eq 323) "schema rows expected 323, got $($schema.Count)";Check ($fields.Count -eq 120) "fields rows expected 120, got $($fields.Count)";Check ($req.Count -eq 792) "requirements expected 792, got $($req.Count)";Check ($facts.Count -eq 621) "facts guard expected 621, got $($facts.Count)"
$fh='field_id|field_domain|field_name_zh|definition|value_kind|canonical_unit|value_enum_name|allowed_subject_kinds|condition_schema|required_tier|review_status|notes';$rh='requirement_id|object_id|component_id|link_id|object_relation_id|precision_path_id|capability_id|topology_id|field_id|requirement_status|applicability_reason|search_status|last_searched_date|requirement_fingerprint|review_status|notes'
Check ((($fields|Select-Object -First 1).PSObject.Properties.Name-join'|') -ceq $fh) 'formal fields header is not frozen 12-column baseline';Check ((($req|Select-Object -First 1).PSObject.Properties.Name-join'|') -ceq $rh) 'formal requirements header changed';Check (@($schema|Where-Object{$_.table_path -eq '数据/fields.csv' -and $_.column_name -eq 'allowed_requirement_target_kinds'}).Count -eq 0) 'new schema column already exists; preflight baseline stale';Check ( -not (($fields|Select-Object -First 1).PSObject.Properties.Name-contains'allowed_requirement_target_kinds')) 'new fields column already exists; preflight baseline stale'
$df=@($fields|Where-Object field_id -eq 'FIELD-DER-COMPUTE-BW-SPEC');$cf=@($fields|Where-Object field_id -eq 'FIELD-PHY-CLOCK');Check ($df.Count -eq 1 -and $df[0].allowed_subject_kinds -ceq 'object') 'DER current fact contract is not object';Check ($cf.Count -eq 1 -and $cf[0].allowed_subject_kinds -ceq 'object') 'CLOCK current fact contract is not object'
$sp=Join-Path $cand 'validation-summary.json'
if(Test-Path -LiteralPath $sp){$sum=Get-Content -LiteralPath $sp -Raw -Encoding UTF8|ConvertFrom-Json;Check ([int]$sum.preaudit_rows -eq 132 -and [int]$sum.unique_pks -eq 132) 'summary must cover 132 unique preaudit rows';Check ([int]$sum.fields -eq 26 -and [int]$sum.groups -eq 28) 'summary must cover 26 fields and 28 groups';Check ([int]$sum.fact_rows -eq 8 -and [int]$sum.requirement_rows -eq 124) 'summary must cover 8 facts and 124 requirements';Check ([int]$sum.action_counts.expand_contract -eq 12 -and [int]$sum.action_counts.retarget_row -eq 12 -and [int]$sum.action_counts.no_change_with_rationale -eq 108) 'summary action counts must be 12/12/108';Check ([int]$sum.overlay_rows -eq 12 -and [int]$sum.field_proposals -eq 26) 'summary overlay/proposal counts wrong';Check ([string]$sum.canonical_kind_order -ceq ($Kinds-join';')) 'summary canonical kind order wrong';foreach($x in $sum.input_sha256.PSObject.Properties){$p=Full $root $x.Name;Check (Test-Path -LiteralPath $p -PathType Leaf) "summary input missing: $($x.Name)";if(Test-Path -LiteralPath $p){Check ((Hash $p) -ceq ([string]$x.Value).ToLowerInvariant()) "candidate input hash stale: $($x.Name)"}}}
$ap=Join-Path $cand 'adjudication.csv';$pp=Join-Path $cand 'field-contract-proposals.csv';$op=Join-Path $cand 'row-overlay-proposals.csv'
if((Test-Path -LiteralPath $ap) -and (Test-Path -LiteralPath $pp) -and (Test-Path -LiteralPath $op)){$adj=@(Import-Csv -LiteralPath $ap);$prop=@(Import-Csv -LiteralPath $pp);$ov=@(Import-Csv -LiteralPath $op);Check ($adj.Count -eq 132) 'adjudication rows not 132';Check (@($adj|Group-Object table_path,pk|Where-Object Count -ne 1).Count -eq 0) 'adjudication keys not unique';Check (@($adj|Where-Object proposed_action -eq 'expand_contract').Count -eq 12) 'adjudication expand count not 12';Check (@($adj|Where-Object proposed_action -eq 'retarget_row').Count -eq 12) 'adjudication retarget count not 12';Check (@($adj|Where-Object proposed_action -eq 'no_change_with_rationale').Count -eq 108) 'adjudication no-change count not 108';Check (@($adj|Where-Object table_path -eq '数据/facts.csv').Count -eq 8) 'adjudication fact rows not 8';Check (@($adj|Where-Object table_path -eq '数据/field-requirements.csv').Count -eq 124) 'adjudication requirement rows not 124';Check (@($adj|Where-Object{ -not (Blank $_.blocking_reason) -or $_.review_status -ne 'reviewed'}).Count -eq 0) 'adjudication has blocker or unreviewed row'
$ph='field_id|current_fact_allowed_subject_kinds|proposed_fact_allowed_subject_kinds|proposed_requirement_target_kinds|proposal_kind|affected_fact_rows|affected_requirement_rows|semantic_rationale|evidence_basis|confidence|blocking_reason|review_status';$oh='table_path|pk|field_id|overlay_action|current_target_kind|current_target_id|proposed_target_kind|proposed_target_id|proposed_field_id|current_requirement_fingerprint|proposed_requirement_fingerprint|rationale|confidence|blocking_reason|review_status';Check ((($prop|Select-Object -First 1).PSObject.Properties.Name-join'|') -ceq $ph) 'proposal header wrong';Check ((($ov|Select-Object -First 1).PSObject.Properties.Name-join'|') -ceq $oh) 'overlay header wrong';Check ($prop.Count -eq 26 -and @($prop|Group-Object field_id|Where-Object Count -ne 1).Count -eq 0) 'proposals must be 26 unique fields';Check ($ov.Count -eq 12 -and @($ov|Group-Object pk|Where-Object Count -ne 1).Count -eq 0) 'overlays must be 12 unique requirements';Check (@($prop|Where-Object{ -not (Blank $_.blocking_reason) -or $_.review_status -ne 'reviewed'}).Count -eq 0) 'proposal blocker or status wrong';Check (@($ov|Where-Object{$_.table_path -ne '数据/field-requirements.csv' -or $_.overlay_action -ne 'retarget_row' -or -not (Blank $_.blocking_reason) -or $_.review_status -ne 'reviewed'}).Count -eq 0) 'overlay scope, blocker, or status wrong'
$auth=@(Import-Csv -LiteralPath (Join-Path $PSScriptRoot 'authorized-overlays.csv'));Check ($auth.Count -eq 12) 'authorized overlay manifest must have 12 rows'
foreach($a in $auth){$x=@($ov|Where-Object pk -eq $a.pk);Check ($x.Count -eq 1) "authorized overlay missing: $($a.pk)";if($x.Count -eq 1){$x=$x[0];Check ($x.field_id -ceq $a.field_id -and $x.proposed_field_id -ceq $a.field_id) "overlay field drift: $($a.pk)";Check ($x.current_target_kind -ceq $a.current_kind -and $x.current_target_id -ceq $a.current_id) "overlay current target drift: $($a.pk)";Check ($x.proposed_target_kind -ceq $a.proposed_kind -and $x.proposed_target_id -ceq $a.proposed_id) "overlay proposed target drift: $($a.pk)"}}
$ovBy=@{};foreach($x in $ov){$ovBy[$x.pk]=$x};$rBy=@{};foreach($x in $req){$rBy[$x.requirement_id]=$x};$cells=0;$fps=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach($r in $req){$fp=[string]$r.requirement_fingerprint;if($ovBy.ContainsKey($r.requirement_id)){$x=$ovBy[$r.requirement_id];$k=Kind $r;$id=if(Blank $k){''}else{[string]$r.($Col[$k])};Check ($k -ceq $x.current_target_kind -and $id -ceq $x.current_target_id) "overlay current formal target mismatch: $($r.requirement_id)";$cur=ReqFp $r;Check ($cur -ceq $x.current_requirement_fingerprint) "current fingerprint mismatch: $($r.requirement_id)";$fp=ReqFp $r $x.proposed_target_kind $x.proposed_target_id $x.proposed_field_id;Check ($fp -ceq $x.proposed_requirement_fingerprint) "proposed fingerprint mismatch: $($r.requirement_id)";if($x.current_target_kind -ceq $x.proposed_target_kind){$cells+=2}else{$cells+=3}};Check ($fps.Add($fp)) "post-overlay fingerprint duplicate: $fp"}
Check ($cells -eq 32) "overlay cell delta expected 32, got $cells"
$fBy=@{};foreach($f in $fields){$fBy[$f.field_id]=$f};$pBy=@{}
foreach($p0 in $prop){$pBy[$p0.field_id]=$p0;Check ($fBy.ContainsKey($p0.field_id)) "proposal field missing: $($p0.field_id)";if($fBy.ContainsKey($p0.field_id)){Check ($p0.current_fact_allowed_subject_kinds -ceq $fBy[$p0.field_id].allowed_subject_kinds) "proposal current contract stale: $($p0.field_id)"};Contract $p0.proposed_fact_allowed_subject_kinds "$($p0.field_id).fact";Contract $p0.proposed_requirement_target_kinds "$($p0.field_id).requirement"}
$fc=@($prop|Where-Object{$_.current_fact_allowed_subject_kinds -cne $_.proposed_fact_allowed_subject_kinds});Check ($fc.Count -eq 2) "fact contract changes expected 2, got $($fc.Count)";$d=@($fc|Where-Object field_id -eq 'FIELD-DER-COMPUTE-BW-SPEC');$c=@($fc|Where-Object field_id -eq 'FIELD-PHY-CLOCK');Check ($d.Count -eq 1 -and $d[0].proposed_fact_allowed_subject_kinds -ceq 'object;precision_path') 'DER proposed fact contract wrong';Check ($c.Count -eq 1 -and $c[0].proposed_fact_allowed_subject_kinds -ceq 'object;component') 'CLOCK proposed fact contract wrong'
$factAllow=@{};$reqAllow=@{};foreach($f in $fields){if($pBy.ContainsKey($f.field_id)){$factAllow[$f.field_id]=[string]$pBy[$f.field_id].proposed_fact_allowed_subject_kinds;$reqAllow[$f.field_id]=[string]$pBy[$f.field_id].proposed_requirement_target_kinds}else{$factAllow[$f.field_id]=[string]$f.allowed_subject_kinds;$reqAllow[$f.field_id]=[string]$f.allowed_subject_kinds}}
foreach($f in $facts){$k=Kind $f;Check ( -not (Blank $k) -and $k -in $factAllow[$f.field_id].Split(';')) "post-proposal fact contract miss: $($f.fact_id)"}
foreach($f in $fields){$set=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal);foreach($k in $factAllow[$f.field_id].Split(';')){[void]$set.Add($k)};foreach($r in $req|Where-Object field_id -eq $f.field_id){$k=Kind $r;if($ovBy.ContainsKey($r.requirement_id)){$k=$ovBy[$r.requirement_id].proposed_target_kind};if( -not (Blank $k)){[void]$set.Add($k)}};$minimal=@($Kinds|Where-Object{$set.Contains($_)})-join';';Check ($reqAllow[$f.field_id] -ceq $minimal) "nonminimal requirement contract: $($f.field_id); got=$($reqAllow[$f.field_id]); expected=$minimal"}
$rel=@(Import-Csv -LiteralPath (Full $root '数据/object-relations.csv'))
foreach($r in $req|Where-Object{$_.requirement_status -in @('value_available','conflicting_unresolved')}){$k=Kind $r;$id=if(Blank $k){''}else{[string]$r.($Col[$k])};if($ovBy.ContainsKey($r.requirement_id)){$k=$ovBy[$r.requirement_id].proposed_target_kind;$id=$ovBy[$r.requirement_id].proposed_target_id};if($r.field_id -eq 'FIELD-ID-ARCH'){$z=@($rel|Where-Object object_relation_id -eq $id);Check ($k -eq 'object_relation' -and $z.Count -eq 1 -and $z[0].relation_type -eq 'implements_architecture') "invalid architecture projection: $($r.requirement_id)"}else{$v=if($ovBy.ContainsKey($r.requirement_id)){Vec $r $k $id}else{Vec $r};$z=@($facts|Where-Object{$_.field_id -eq $r.field_id -and (Vec $_) -ceq $v});Check ($z.Count -gt 0) "same-target same-field closure miss: $($r.requirement_id)"}}
}# All retargets must resolve inside the original owner object.
$obj=@(Import-Csv -LiteralPath (Full $root '数据/objects.csv'));$cmp=@(Import-Csv -LiteralPath (Full $root '数据/components.csv'));$lnk=@(Import-Csv -LiteralPath (Full $root '数据/links.csv'));$pth=@(Import-Csv -LiteralPath (Full $root '数据/precision-paths.csv'));$cap=@(Import-Csv -LiteralPath (Full $root '数据/special-capabilities.csv'));$top=@(Import-Csv -LiteralPath (Full $root '数据/topologies.csv'))
function Owner([string]$k,[string]$id){switch($k){'object'{if(@($obj|Where-Object object_id -eq $id).Count -eq 1){return $id}};'component'{$z=@($cmp|Where-Object component_id -eq $id);if($z.Count -eq 1){return $z[0].owner_object_id}};'link'{$z=@($lnk|Where-Object link_id -eq $id);if($z.Count -eq 1){return $z[0].owner_object_id}};'object_relation'{$z=@($rel|Where-Object object_relation_id -eq $id);if($z.Count -eq 1){return $z[0].subject_object_id}};'precision_path'{$z=@($pth|Where-Object precision_path_id -eq $id);if($z.Count -eq 1){$y=@($cmp|Where-Object component_id -eq $z[0].component_id);if($y.Count -eq 1){return $y[0].owner_object_id}}};'capability'{$z=@($cap|Where-Object capability_id -eq $id);if($z.Count -eq 1){return $z[0].owner_object_id}};'topology'{$z=@($top|Where-Object topology_id -eq $id);if($z.Count -eq 1){return $z[0].owner_object_id}}};return ''}
foreach($x in $ov){$a=Owner $x.current_target_kind $x.current_target_id;$b=Owner $x.proposed_target_kind $x.proposed_target_id;Check ( -not (Blank $a) -and $a -ceq $b) "overlay owner mismatch: $($x.pk); old=$a new=$b"}
# Recompute the candidate tables and the exact authorized delta without writing them.
$cs=@(Import-Csv -LiteralPath (Join-Path $cand 'candidate-schema-columns.csv'));$cfld=@(Import-Csv -LiteralPath (Join-Path $cand 'candidate-fields.csv'));$creq=@(Import-Csv -LiteralPath (Join-Path $cand 'candidate-field-requirements.csv'))
Check ($cs.Count -eq 324) 'candidate schema must contain 324 rows';Check ($cfld.Count -eq 120) 'candidate fields must contain 120 rows';Check ($creq.Count -eq 792) 'candidate requirements must contain 792 rows'
foreach($n in @('candidate-schema-columns.csv','candidate-fields.csv','candidate-field-requirements.csv')){$q=Profile (Join-Path $cand $n);Check ($q.valid -and -not $q.bom -and $q.bare_lf -eq 0 -and $q.bare_cr -eq 0 -and $q.crlf -gt 0 -and $q.final) "candidate CSV encoding/newline wrong: $n"}
$nr=@($cs|Where-Object schema_column_id -eq 'SCOL-FIELDS-CSV-013');Check ($nr.Count -eq 1) 'new schema row missing';if($nr.Count -eq 1){$nr=$nr[0];Check ($nr.table_path -ceq '数据/fields.csv' -and $nr.column_name -ceq 'allowed_requirement_target_kinds' -and $nr.ordinal -ceq '13' -and $nr.data_type -ceq 'text') 'new schema row identity/type wrong';Check ($nr.is_nullable -ceq 'false' -and $nr.is_primary_key -ceq 'false' -and $nr.semicolon_forbidden -ceq 'false' -and $nr.review_status -ceq 'approved') 'new schema row constraints/status wrong'}
$schemaCols=@(($schema|Select-Object -First 1).PSObject.Properties.Name);for($i=0;$i -lt $schema.Count;$i++){Check ($cs[$i].schema_column_id -ceq $schema[$i].schema_column_id) "schema row order drift at $i";foreach($c0 in $schemaCols){Check ([string]$cs[$i].$c0 -ceq [string]$schema[$i].$c0) "unauthorized schema cell drift: $($schema[$i].schema_column_id).$c0"}}
$cfBy=@{};foreach($x in $cfld){$cfBy[$x.field_id]=$x};$baseFieldCols=@(($fields|Select-Object -First 1).PSObject.Properties.Name);foreach($f in $fields){Check ($cfBy.ContainsKey($f.field_id)) "candidate field missing: $($f.field_id)";if(-not $cfBy.ContainsKey($f.field_id)){continue};$x=$cfBy[$f.field_id];foreach($c0 in $baseFieldCols){if($c0 -eq 'allowed_subject_kinds'){Check ([string]$x.$c0 -ceq $factAllow[$f.field_id]) "candidate fact contract mismatch: $($f.field_id)"}else{Check ([string]$x.$c0 -ceq [string]$f.$c0) "unauthorized candidate field drift: $($f.field_id).$c0"}};Check ([string]$x.allowed_requirement_target_kinds -ceq $reqAllow[$f.field_id]) "candidate requirement contract mismatch: $($f.field_id)"}
$crBy=@{};foreach($x in $creq){$crBy[$x.requirement_id]=$x};$reqCols=@(($req|Select-Object -First 1).PSObject.Properties.Name);foreach($r in $req){Check ($crBy.ContainsKey($r.requirement_id)) "candidate requirement missing: $($r.requirement_id)";if(-not $crBy.ContainsKey($r.requirement_id)){continue};$x=$crBy[$r.requirement_id];foreach($c0 in $reqCols){$expected=[string]$r.$c0;if($ovBy.ContainsKey($r.requirement_id)){$o=$ovBy[$r.requirement_id];if($c0 -eq $Col[$o.current_target_kind]){$expected=''};if($c0 -eq $Col[$o.proposed_target_kind]){$expected=$o.proposed_target_id};if($c0 -eq 'requirement_fingerprint'){$expected=$o.proposed_requirement_fingerprint}};Check ([string]$x.$c0 -ceq $expected) "unauthorized candidate requirement drift: $($r.requirement_id).$c0"}}
$mm=@(Import-Csv -LiteralPath (Join-Path $cand 'formal-migration-manifest.csv'));Check ($mm.Count -eq 166) 'formal migration manifest must contain 166 cell/file entries';Check (@($mm|Where-Object target_path -eq '数据/fields.csv').Count -eq 122) 'field manifest delta must be 122';Check (@($mm|Where-Object target_path -eq '数据/schema-columns.csv').Count -eq 11) 'schema manifest must describe one 11-cell inserted row';Check (@($mm|Where-Object target_path -eq '数据/field-requirements.csv').Count -eq 32) 'requirement manifest delta must be 32';Check (@($mm|Where-Object target_path -eq 'scripts/validation/Validate-ResearchData.ps1').Count -eq 1) 'validator manifest must be one exact file replacement'
$vs=Get-Content -LiteralPath (Join-Path $cand 'verification-summary.json') -Raw -Encoding UTF8|ConvertFrom-Json;Check ($vs.verdict -ceq 'accept' -and [int]$vs.formal_baseline_validator_checks -eq 93378) 'candidate verification summary lacks 93,378-check accept';Check ([int]$vs.negative_tests -eq 6 -and [int]$vs.negative_tests_passed -eq 6) 'candidate negative tests are incomplete';Check ($vs.candidate_csv_utf8_no_bom -eq $true -and $vs.candidate_csv_crlf_only -eq $true -and $vs.candidate_csv_final_crlf -eq $true) 'candidate CSV format summary wrong'
$vp=Join-Path $cand 'Validate-ResearchData.ps1'
if(Test-Path -LiteralPath $vp){$tok=$null;$pe=$null;[void][Management.Automation.Language.Parser]::ParseFile($vp,[ref]$tok,[ref]$pe);Check ($pe.Count -eq 0) "candidate validator parse errors: $($pe-join'; ')";$vt=Get-Content -LiteralPath $vp -Raw -Encoding UTF8;foreach($pattern in @("ValidateSet\('audit','gate'\)","SubjectContractMode\s*=\s*'gate'",'allowed_subject_kinds','allowed_requirement_target_kinds','value_available','conflicting_unresolved','FIELD-ID-ARCH','implements_architecture','same-target same-field fact')){Check ($vt -match $pattern) "validator missing contract token: $pattern"};Check ( -not ($vt -match '(?im)^\s*(Set-Content|Add-Content|Out-File|Export-Csv|Copy-Item|Move-Item|Remove-Item|New-Item)\b|\[System\.IO\.File\]::Write')) 'candidate validator contains filesystem write';$vprof=Profile $vp;Check ($vprof.valid -and $vprof.bom) 'candidate validator must be valid UTF-8 with BOM';Check ($vprof.bare_cr -eq 0 -and $vprof.bare_lf -gt 0) 'candidate validator must use LF as primary newline and no bare CR';Check ( -not $vprof.final) 'candidate validator must have no final newline';Write-Output "CANDIDATE-VALIDATOR-BYTES: sha256=$(Hash $vp); bytes=$($vprof.bytes); crlf=$($vprof.crlf); bare_lf=$($vprof.bare_lf); final_newline=$($vprof.final)"}
$fr=Join-Path $cand 'formal-validator-readonly-run.txt';if(Test-Path -LiteralPath $fr){$t=Get-Content -LiteralPath $fr -Raw -Encoding UTF8;Check ($t -match 'PASS: 32-table research data model; 93378 checks executed\.') 'candidate formal run not refreshed to 93,378';Check ($t -match 'Registry: 323 columns, 488 enum values\.') 'candidate formal run registry wrong'}
if(Blank $IndependentReviewPath){Warn 'technical preflight does not include an independent exact-accept signoff'}else{$rp=Full $root $IndependentReviewPath;Check (Test-Path -LiteralPath $rp -PathType Leaf) "review missing: $rp";if(Test-Path -LiteralPath $rp){$rt=Get-Content -LiteralPath $rp -Raw -Encoding UTF8;Check ($rt -match '(?m)^裁决[：:]\s*`?accept`?\s*$') 'independent review is not exact accept'}}
foreach($e in $manifest){$p=Full $root $e.path;if(Test-Path -LiteralPath $p){Check ((Hash $p) -ceq $start[$e.path]) "formal input changed during preflight: $($e.path)"}}
foreach($n in $candStart.Keys){$p=Join-Path $cand $n;Check (Test-Path -LiteralPath $p) "candidate disappeared: $n";if(Test-Path -LiteralPath $p){Check ((Hash $p) -ceq $candStart[$n]) "candidate changed during preflight: $n"}}
foreach($m in $script:Warnings){Write-Output "WARNING: $m"}
if($script:Errors.Count){Write-Output "FAIL: $($script:Errors.Count) preflight error(s); $($script:Checks) checks executed.";foreach($m in $script:Errors){Write-Output " - $m"};exit 1}
Write-Output "PASS: field-contract migration technical preflight; $($script:Checks) checks executed."
Write-Output 'Expected delta: schema +1 row; fields +1 column/120 values and 2 fact-contract cells; requirements 12 rows/32 cells; validator exact-byte replacement; facts/enums unchanged.'
Write-Output 'This read-only result does not authorize migration without independent exact accept and byte-for-byte backup.'
exit 0