param([string]$Root='D:\Workspace\2026projects\调研-训练推理芯片调研-资料汇总')
$ErrorActionPreference='Stop'
$Pkg=Join-Path $Root '审计\子代理交接\m2_staging\M2-W3-HUAWEI-ASCEND950-PHYSICAL';$Out=Join-Path $Pkg 'structured'
$Schema=Import-Csv -LiteralPath (Join-Path $Root '数据\schema-columns.csv');$Bom=New-Object Text.UTF8Encoding($true)
function NR($tp,[System.Collections.IDictionary]$v){$cs=@($Schema|? table_path -eq $tp|sort {[int]$_.ordinal}|% column_name);$o=[ordered]@{};foreach($c in $cs){$o[$c]=''};foreach($k in $v.Keys){if(!$o.Contains($k)){throw "$tp bad col $k"};$o[$k]=[string]$v[$k]};[pscustomobject]$o}
function WT($tp,[object[]]$rs){$cs=@($Schema|? table_path -eq $tp|sort {[int]$_.ordinal}|% column_name);$f=Join-Path $Out ([IO.Path]::GetFileName($tp));$a=@($rs);if($a.Count){$a|select $cs|Export-Csv -LiteralPath $f -NoTypeInformation -Encoding UTF8}else{[IO.File]::WriteAllText($f,'"'+($cs -join '","')+'"'+[Environment]::NewLine,$Bom)}}
$D='OBJ-HUAWEI-ASCEND-950-DIE';$P='OBJ-HUAWEI-ASCEND-950PR';$T='OBJ-HUAWEI-ASCEND-950DT'
$H2='SRC-M2W3-HUAWEI-H2-ASC950-KEYNOTE-20250918';$H6='SRC-M2W3-HUAWEI-H6-PROCESSOR-20260813';$H7='SRC-M2W3-HUAWEI-H7-ACCELERATOR-CARD-20260813';$H12='SRC-M2W3-HUAWEI-H12-ATLAS350-LAUNCH-20260320'
$comps=[Collections.Generic.List[object]]::new();$mem=[Collections.Generic.List[object]]::new();$links=[Collections.Generic.List[object]]::new();$pps=[Collections.Generic.List[object]]::new();$conds=[Collections.Generic.List[object]]::new();$facts=[Collections.Generic.List[object]]::new();$ass=[Collections.Generic.List[object]]::new();$req=[Collections.Generic.List[object]]::new();$revid=[Collections.Generic.List[object]]::new();$logs=[Collections.Generic.List[object]]::new();$results=[Collections.Generic.List[object]]::new();$cc=[Collections.Generic.List[object]]::new();$fams=[Collections.Generic.List[object]]::new();$src=[Collections.Generic.List[object]]::new();$ends=[Collections.Generic.List[object]]::new();$screen=[Collections.Generic.List[object]]::new();$roles=[Collections.Generic.List[object]]::new();$cov=[Collections.Generic.List[object]]::new();$runs=[Collections.Generic.List[object]]::new();$members=[Collections.Generic.List[object]]::new()
function AF($id,$kind,$sid,$field,$txt,$num,$unit,$cond,$ev,$from,$conf,$why,$note){$v=[ordered]@{fact_id=$id;field_id=$field;normalized_value_text=$txt;normalized_value_number=$num;normalized_unit=$unit;condition_set_id=$cond;fact_kind='direct_statement';evidence_state=$ev;resolution_state='provisional';valid_from=$from;confidence=$conf;confidence_reason=$why;fact_fingerprint="$kind|$sid|$field|$txt|$num|$unit|$cond";review_status='draft';notes=$note};$v[(@{object='object_id';component='component_id';link='link_id';precision_path='precision_path_id'}[$kind])]=$sid;$facts.Add((NR '数据/facts.csv' $v))}
function AA($id,$fid,$sid,$role,$rel,$txt,$num,$unit,$loc,$ctx,$note){$ass.Add((NR '最小参考资料库/fact-assertions.csv' ([ordered]@{assertion_id=$id;fact_id=$fid;source_id=$sid;claim_role=$role;assertion_mode='direct_statement';assertion_relation=$rel;raw_value_text=$txt;raw_value_number=$num;raw_unit=$unit;source_locator=$loc;quoted_context=$ctx;extraction_status='source_checked';extractor='m2_w3_huawei_asc950_physical';review_date='2026-08-13';assertion_fingerprint="$fid|$sid|$rel|$loc";review_status='draft';notes=$note})))}
function AR($id,$kind,$tid,$field,$status,$why,$note){$v=[ordered]@{requirement_id=$id;field_id=$field;requirement_status=$status;applicability_reason=$why;search_status='completed';last_searched_date='2026-08-13';requirement_fingerprint="$kind|$tid|$field";review_status='draft';notes=$note};$v[(@{object='object_id';component='component_id';link='link_id';precision_path='precision_path_id'}[$kind])]=$tid;$req.Add((NR '数据/field-requirements.csv' $v));if($status-eq'not_found'){$q=$id-replace'^REQ-','SEARCH-';$logs.Add((NR '最小参考资料库/search-log.csv' ([ordered]@{search_id=$q;requirement_id=$id;searched_date='2026-08-13';query_or_path="Requirement-specific exact-object review for $id ($field): H-2, H-6 plus DT route, H-7, H-12.";source_types_checked='conference_talk;product_page;press_release';result_status='no_reliable_result';researcher='m2_w3_huawei_asc950_physical';review_status='draft';notes=$why})));$ss=@($H2,$H6,$H7,$H12);$tt=@('H2','H6','H7','H12');for($i=0;$i-lt4;$i++){$n=if($i-eq2){'Card-level material checked only for boundary; it cannot fill die/package fields.'}elseif($i-eq1){'Processor page and DT renderer state checked; no exact supporting value.'}else{'Official source checked; no exact supporting value.'};$results.Add((NR '最小参考资料库/search-results.csv' ([ordered]@{search_result_id="SRESULT-$($id.Substring(4))-$($tt[$i])";search_id=$q;source_id=$ss[$i];result_relation='checked_no_support';review_status='draft';notes=$n})))}}}
$defs=@(@('COMP-M2W3-HUAWEI-ASC950-DIE-AI-PEAK',$D,'compute','other_fixed_function','Ascend 950 vendor-labeled low-precision compute path'),@('COMP-M2W3-HUAWEI-ASC950-DIE-VECTOR',$D,'compute','vector','Ascend 950 vector path'),@('COMP-M2W3-HUAWEI-ASC950-DIE-MEMACCESS',$D,'data_movement','load_store','Ascend 950 memory access path'),@('COMP-M2W3-HUAWEI-ASC950PR-VENDOR-PEAK',$P,'compute','other_fixed_function','Ascend 950PR unresolved maximum path'),@('COMP-M2W3-HUAWEI-ASC950PR-HIBL1',$P,'memory','memory_level','Ascend 950PR HiBL 1.0 HBM'),@('COMP-M2W3-HUAWEI-ASC950DT-HIZQ2',$T,'memory','memory_level','Ascend 950DT HiZQ 2.0 HBM'))
foreach($x in $defs){$comps.Add((NR '数据/components.csv' ([ordered]@{component_id=$x[0];owner_object_id=$x[1];component_domain=$x[2];component_type=$x[3];canonical_label=$x[4];review_status='draft';notes='Exact object scope; no card or system aggregate.'})))}
$mem.Add((NR '数据/memory-levels.csv' ([ordered]@{memory_level_id='COMP-M2W3-HUAWEI-ASC950PR-HIBL1';level_class='hbm';canonical_label='Ascend 950PR HiBL 1.0 HBM';review_status='draft';notes='Package-specific; parent hierarchy unknown.'})));$mem.Add((NR '数据/memory-levels.csv' ([ordered]@{memory_level_id='COMP-M2W3-HUAWEI-ASC950DT-HIZQ2';level_class='hbm';canonical_label='Ascend 950DT HiZQ 2.0 HBM';review_status='draft';notes='Package-specific roadmap memory.'})))
foreach($x in @(@('LINK-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT',$D,'Ascend 950 common chip interconnect'),@('LINK-M2W3-HUAWEI-ASC950PR-LINGQU2',$P,'Ascend 950PR Lingqu 2.0'),@('LINK-M2W3-HUAWEI-ASC950DT-INTERCONNECT',$T,'Ascend 950DT total interconnect'))){$links.Add((NR '数据/links.csv' ([ordered]@{link_id=$x[0];owner_object_id=$x[1];endpoint_a_id=$x[1];link_level='device_direct';canonical_label=$x[2];review_status='draft';notes='No per-link, payload or topology inference.'})))}
foreach($x in @(@('FP8','FP8'),@('MXFP8','MXFP8'),@('HIF8','HiF8'),@('MXFP4','MXFP4'))){$pps.Add((NR '数据/precision-paths.csv' ([ordered]@{precision_path_id="PPATH-M2W3-HUAWEI-ASC950-DIE-$($x[0])";component_id='COMP-M2W3-HUAWEI-ASC950-DIE-AI-PEAK';canonical_label="Ascend 950 $($x[1]) vendor-labeled path";operation_class='other';review_status='needs_resolution';notes='Common chip label stored once on shared die; no matrix/vector/count inference.'})))}
$pps.Add((NR '数据/precision-paths.csv' ([ordered]@{precision_path_id='PPATH-M2W3-HUAWEI-ASC950PR-VENDOR-MAX';component_id='COMP-M2W3-HUAWEI-ASC950PR-VENDOR-PEAK';canonical_label='Ascend 950PR maximum TFLOPS path, datatype unresolved';operation_class='other';review_status='needs_resolution';notes='H-6 omits datatype and operation count.'})))
foreach($x in @(@('FP8','FP8'),@('MXFP8','MXFP8'),@('HIF8','HiF8'),@('MXFP4','MXFP4'))){$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id="COND-M2W3-HUAWEI-ASC950-DIE-$($x[0])-ROADMAP";condition_fingerprint="Asc950-die|$($x[1])|vendor-unresolved|2025-09-18";precision_path_id="PPATH-M2W3-HUAWEI-ASC950-DIE-$($x[0])";sparsity_mode='not_specified';operation_type='';operation_count_rule='vendor_label';performance_basis='vendor_label_unresolved';support_level='hardware_peak_published';workload_stage='not_specified';measurement_scope='per_object';effective_date='2025-09-18';review_status='needs_resolution';notes='Future common-series label; matrix/vector, density, count rule, power and frequency unresolved.'})))}
$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id='COND-M2W3-HUAWEI-ASC950-DIE-MECHANISM-ROADMAP';condition_fingerprint='Asc950-die|mechanisms|2025-09-18';sparsity_mode='not_applicable';operation_type='data_move';operation_count_rule='not_specified';performance_basis='vendor_label_unresolved';support_level='hardware_capability';workload_stage='not_specified';measurement_scope='per_object';effective_date='2025-09-18';review_status='needs_resolution';notes='Future common-series mechanism stored once on shared die.'})))
$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id='COND-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT-ROADMAP';condition_fingerprint='Asc950-die|2TBps|direction-unknown|2025-09-18';sparsity_mode='not_applicable';operation_type='data_move';operation_count_rule='not_specified';performance_basis='vendor_label_unresolved';support_level='hardware_peak_published';workload_stage='not_specified';bandwidth_direction='direction_not_specified';aggregation_scope='per_endpoint';traffic_basis='vendor_nameplate';measurement_scope='per_object';effective_date='2025-09-18';review_status='needs_resolution';notes='Common-series aggregate label; direction and payload unknown.'})))
$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id='COND-M2W3-HUAWEI-ASC950PR-EMBEDDED-STATUS-20260320';condition_fingerprint='Asc950PR|Atlas350-embedded|available|2026-03-20';sparsity_mode='not_applicable';operation_type='fixed_function';operation_count_rule='not_specified';performance_basis='vendor_label_unresolved';support_level='hardware_capability';workload_stage='serving';measurement_scope='per_object';effective_date='2026-03-20';review_status='needs_resolution';notes='Available only through officially launched Atlas 350; no standalone sale or delivery claim.'})))
$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id='COND-M2W3-HUAWEI-ASC950PR-MEMORY-CURRENT-20260813';condition_fingerprint='Asc950PR|HiBL1|max-128GB-1.6TBps|2026-08-13';sparsity_mode='not_applicable';operation_type='data_move';operation_count_rule='not_specified';performance_basis='vendor_label_unresolved';support_level='hardware_capability';workload_stage='prefill';bandwidth_direction='direction_not_specified';aggregation_scope='per_endpoint';traffic_basis='vendor_nameplate';measurement_scope='per_object';effective_date='2026-08-13';review_status='draft';notes='Current PR page; maximum capacity and nameplate bandwidth.'})))
$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id='COND-M2W3-HUAWEI-ASC950PR-VENDOR-MAX-CURRENT-20260813';condition_fingerprint='Asc950PR|1784TFLOPS|datatype-count-unresolved|2026-08-13';precision_path_id='PPATH-M2W3-HUAWEI-ASC950PR-VENDOR-MAX';sparsity_mode='not_specified';operation_type='';operation_count_rule='vendor_label';performance_basis='vendor_label_unresolved';support_level='hardware_peak_published';workload_stage='prefill';measurement_scope='per_object';effective_date='2026-08-13';review_status='needs_resolution';notes='No datatype, operation class, density, count, power or frequency.'})))
$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id='COND-M2W3-HUAWEI-ASC950PR-LINGQU2-CURRENT-20260813';condition_fingerprint='Asc950PR|Lingqu2|max2TBps|bidir|2026-08-13';sparsity_mode='not_applicable';operation_type='data_move';operation_count_rule='not_specified';performance_basis='vendor_label_unresolved';support_level='hardware_peak_published';workload_stage='not_specified';bandwidth_direction='bidirectional_aggregate';aggregation_scope='per_endpoint';traffic_basis='vendor_nameplate';measurement_scope='per_object';effective_date='2026-08-13';review_status='draft';notes='Maximum bidirectional aggregate; no per-link or payload data.'})))
$conds.Add((NR '数据/condition-sets.csv' ([ordered]@{condition_set_id='COND-M2W3-HUAWEI-ASC950DT-ROADMAP-20250918';condition_fingerprint='Asc950DT|HiZQ2-and-total-link|direction-unknown|2025-09-18';sparsity_mode='not_applicable';operation_type='data_move';operation_count_rule='not_specified';performance_basis='vendor_label_unresolved';support_level='hardware_peak_published';workload_stage='training';bandwidth_direction='direction_not_specified';aggregation_scope='per_endpoint';traffic_basis='vendor_nameplate';measurement_scope='per_object';effective_date='2025-09-18';review_status='needs_resolution';notes='Future DT roadmap, not GA, delivery or sustained-performance evidence.'})))
$sw='H-2 first states PR and DT use the same die, then gives a common Ascend 950 chips statement; stored once on the die with caveat.'
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-VENDOR' object $D 'FIELD-ID-VENDOR' Huawei '' '' 'COND-NONE' single_source '' high 'Official Huawei keynote.' 'Publisher identity.'
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-FAMILY' object $D 'FIELD-ID-FAMILY' 'Ascend 950 series' '' '' 'COND-NONE' single_source '' high 'Exact H-2 series label.' ''
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-NAME' object $D 'FIELD-ID-NAME' 'Huawei Ascend 950 die' '' '' 'COND-NONE' single_source '' high 'H-2 explicitly names Ascend 950 Die.' ''
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-OBJECT-TYPE' object $D 'FIELD-ID-OBJECT-TYPE' die '' '' 'COND-NONE' single_source '' high 'H-2 uses the exact term Die.' ''
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-RELEASE-DATE' object $D 'FIELD-ID-RELEASE-DATE' '2025-09-18' '' '' 'COND-NONE' single_source '2025-09-18' high 'Dated official first disclosure.' 'Announcement, not availability.'
foreach($x in @(@('FP8','1000000000000000'),@('MXFP8','1000000000000000'),@('HIF8','1000000000000000'),@('MXFP4','2000000000000000'))){AF "FACT-M2W3-HUAWEI-ASC950-DIE-$($x[0])-THROUGHPUT" precision_path "PPATH-M2W3-HUAWEI-ASC950-DIE-$($x[0])" 'FIELD-COMP-THROUGHPUT' '' $x[1] 'FLOP/s' "COND-M2W3-HUAWEI-ASC950-DIE-$($x[0])-ROADMAP" source_with_caveat '2025-09-18' medium $sw 'Vendor label unresolved; no matrix/vector or dense/sparse inference.'}
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-VECTOR-EXECUTION' component 'COMP-M2W3-HUAWEI-ASC950-DIE-VECTOR' 'FIELD-COMP-EXECUTION' 'Combined SIMD and SIMT vector design' '' '' 'COND-M2W3-HUAWEI-ASC950-DIE-MECHANISM-ROADMAP' source_with_caveat '2025-09-18' medium $sw 'SIMD=single instruction multiple data; SIMT=single instruction multiple threads.'
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-MEM-GRANULARITY' component 'COMP-M2W3-HUAWEI-ASC950-DIE-MEMACCESS' 'FIELD-MEM-GRANULARITY' '' 128 byte 'COND-M2W3-HUAWEI-ASC950-DIE-MECHANISM-ROADMAP' source_with_caveat '2025-09-18' medium $sw 'From 512 to 128 bytes; no memory level named.'
AF 'FACT-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT-BW' link 'LINK-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT' 'FIELD-INT-AGGREGATE-BW' '' 2000000000000 'byte/s' 'COND-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT-ROADMAP' source_with_caveat '2025-09-18' medium $sw 'Direction, payload, topology, count and per-link rate unknown.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-VENDOR' object $P 'FIELD-ID-VENDOR' Huawei '' '' 'COND-NONE' corroborated '' high 'Official H-2 and H-6.' ''
AF 'FACT-M2W3-HUAWEI-ASC950PR-FAMILY' object $P 'FIELD-ID-FAMILY' 'Ascend 950 series' '' '' 'COND-NONE' single_source '' high 'H-2 exact series.' ''
AF 'FACT-M2W3-HUAWEI-ASC950PR-NAME' object $P 'FIELD-ID-NAME' 'Huawei Ascend 950PR' '' '' 'COND-NONE' corroborated '' high 'H-2, H-6 and H-12 exact object.' ''
AF 'FACT-M2W3-HUAWEI-ASC950PR-SKU' object $P 'FIELD-ID-SKU' 'Ascend 950PR' '' '' 'COND-NONE' corroborated '' high 'Three official sources.' ''
AF 'FACT-M2W3-HUAWEI-ASC950PR-OBJECT-TYPE' object $P 'FIELD-ID-OBJECT-TYPE' package '' '' 'COND-NONE' source_with_caveat '' high 'H-2 says HiBL HBM separately packaged with shared die.' 'Formal layer normalization; source also says chip.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-RELEASE-DATE' object $P 'FIELD-ID-RELEASE-DATE' '2025-09-18' '' '' 'COND-NONE' single_source '2025-09-18' high 'Dated official first disclosure.' 'Not availability.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-STATUS' object $P 'FIELD-ID-STATUS' available '' '' 'COND-M2W3-HUAWEI-ASC950PR-EMBEDDED-STATUS-20260320' source_with_caveat '2026-03-20' medium 'H-12 says Atlas 350 carrying PR was officially launched.' 'Embedded commercial use only; no standalone delivery.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-POSITIONING' object $P 'FIELD-ID-VENDOR-POSITIONING' 'Prefill-stage inference and recommendation' '' '' 'COND-NONE' corroborated '' high 'H-2 and H-6 match.' 'Vendor positioning only.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-DEPLOYMENT' object $P 'FIELD-ID-DEPLOYMENT' 'Embedded in officially launched Atlas 350; seven partner systems based on Atlas 350 were presented' '' '' 'COND-M2W3-HUAWEI-ASC950PR-EMBEDDED-STATUS-20260320' source_with_caveat '2026-03-20' high 'Exact H-12 relationship and date.' 'No card specification transferred.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-PACKAGE' object $P 'FIELD-PHY-PACKAGE' 'Ascend 950 die separately packaged with HiBL 1.0 proprietary HBM' '' '' 'COND-NONE' single_source '' high 'Direct H-2 packaging statement.' 'No stack/interposer inference.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-MEM-NAME' component 'COMP-M2W3-HUAWEI-ASC950PR-HIBL1' 'FIELD-MEM-NAME' 'HiBL 1.0 proprietary HBM' '' '' 'COND-M2W3-HUAWEI-ASC950PR-MEMORY-CURRENT-20260813' single_source '' high 'Direct H-2 name.' ''
AF 'FACT-M2W3-HUAWEI-ASC950PR-MEM-CAPACITY' component 'COMP-M2W3-HUAWEI-ASC950PR-HIBL1' 'FIELD-MEM-CAPACITY' '' 128000000000 byte 'COND-M2W3-HUAWEI-ASC950PR-MEMORY-CURRENT-20260813' single_source '2026-08-13' high 'H-6 exact PR body.' 'Decimal GB; maximum package value, not Atlas 350.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-MEM-BW' component 'COMP-M2W3-HUAWEI-ASC950PR-HIBL1' 'FIELD-MEM-BIDIR-BW' '' 1600000000000 'byte/s' 'COND-M2W3-HUAWEI-ASC950PR-MEMORY-CURRENT-20260813' single_source '2026-08-13' high 'H-6 exact PR body.' 'Direction unknown; not sustained.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-VENDOR-MAX-THROUGHPUT' precision_path 'PPATH-M2W3-HUAWEI-ASC950PR-VENDOR-MAX' 'FIELD-COMP-THROUGHPUT' '' 1784000000000000 'FLOP/s' 'COND-M2W3-HUAWEI-ASC950PR-VENDOR-MAX-CURRENT-20260813' source_with_caveat '2026-08-13' medium 'H-6 maximum label; datatype/count unresolved.' 'No matrix/vector or density inference.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-INTERCONNECT-PROTOCOL' link 'LINK-M2W3-HUAWEI-ASC950PR-LINGQU2' 'FIELD-INT-PROTOCOL' 'Lingqu 2.0' '' '' 'COND-M2W3-HUAWEI-ASC950PR-LINGQU2-CURRENT-20260813' single_source '2026-08-13' high 'H-6 exact protocol name.' 'Source says 灵衢2.0.'
AF 'FACT-M2W3-HUAWEI-ASC950PR-INTERCONNECT-BW' link 'LINK-M2W3-HUAWEI-ASC950PR-LINGQU2' 'FIELD-INT-AGGREGATE-BW' '' 2000000000000 'byte/s' 'COND-M2W3-HUAWEI-ASC950PR-LINGQU2-CURRENT-20260813' single_source '2026-08-13' high 'H-6 says maximum 2 TB/s bidirectional.' 'No per-link/payload/topology inference.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-VENDOR' object $T 'FIELD-ID-VENDOR' Huawei '' '' 'COND-NONE' single_source '' high 'Official H-2.' ''
AF 'FACT-M2W3-HUAWEI-ASC950DT-FAMILY' object $T 'FIELD-ID-FAMILY' 'Ascend 950 series' '' '' 'COND-NONE' single_source '' high 'H-2 exact series.' ''
AF 'FACT-M2W3-HUAWEI-ASC950DT-NAME' object $T 'FIELD-ID-NAME' 'Huawei Ascend 950DT' '' '' 'COND-NONE' corroborated '' high 'H-2 plus H-6 route identity.' ''
AF 'FACT-M2W3-HUAWEI-ASC950DT-SKU' object $T 'FIELD-ID-SKU' 'Ascend 950DT' '' '' 'COND-NONE' corroborated '' high 'H-2 plus H-6 route identity.' ''
AF 'FACT-M2W3-HUAWEI-ASC950DT-OBJECT-TYPE' object $T 'FIELD-ID-OBJECT-TYPE' package '' '' 'COND-NONE' source_with_caveat '' high 'H-2 says HiZQ HBM separately packaged with shared die.' 'Formal layer normalization; source also says chip.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-RELEASE-DATE' object $T 'FIELD-ID-RELEASE-DATE' '2025-09-18' '' '' 'COND-NONE' single_source '2025-09-18' high 'Dated official first disclosure.' 'Not availability.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-STATUS' object $T 'FIELD-ID-STATUS' announced '' '' 'COND-NONE' source_with_caveat '2025-09-18' high 'H-2 gives future Q4 2026 window; no GA/delivery evidence by cutoff.' 'Navigation presence does not upgrade status.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-POSITIONING' object $T 'FIELD-ID-VENDOR-POSITIONING' 'Decode-stage inference and model training' '' '' 'COND-NONE' single_source '' high 'Direct H-2 positioning.' 'Roadmap only.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-PACKAGE' object $T 'FIELD-PHY-PACKAGE' 'Ascend 950 die separately packaged with HiZQ 2.0 proprietary HBM' '' '' 'COND-NONE' single_source '' high 'Direct H-2 packaging statement.' 'No stack/interposer inference.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-MEM-NAME' component 'COMP-M2W3-HUAWEI-ASC950DT-HIZQ2' 'FIELD-MEM-NAME' 'HiZQ 2.0 proprietary HBM' '' '' 'COND-M2W3-HUAWEI-ASC950DT-ROADMAP-20250918' single_source '2025-09-18' high 'Direct H-2 name.' 'Roadmap value.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-MEM-CAPACITY' component 'COMP-M2W3-HUAWEI-ASC950DT-HIZQ2' 'FIELD-MEM-CAPACITY' '' 144000000000 byte 'COND-M2W3-HUAWEI-ASC950DT-ROADMAP-20250918' single_source '2025-09-18' high 'H-2 says 144 GB.' 'Decimal GB; roadmap value.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-MEM-BW' component 'COMP-M2W3-HUAWEI-ASC950DT-HIZQ2' 'FIELD-MEM-BIDIR-BW' '' 4000000000000 'byte/s' 'COND-M2W3-HUAWEI-ASC950DT-ROADMAP-20250918' single_source '2025-09-18' high 'H-2 says 4 TB/s memory access bandwidth.' 'Direction/sustained basis unknown; roadmap.'
AF 'FACT-M2W3-HUAWEI-ASC950DT-INTERCONNECT-BW' link 'LINK-M2W3-HUAWEI-ASC950DT-INTERCONNECT' 'FIELD-INT-AGGREGATE-BW' '' 2000000000000 'byte/s' 'COND-M2W3-HUAWEI-ASC950DT-ROADMAP-20250918' single_source '2025-09-18' high 'H-2 says total interconnect will reach 2 TB/s.' 'Direction/per-link/payload/topology unknown; roadmap.'
$lS='H-2 paragraphs beginning At the moment; First; Second; Third';$lP='H-2 paragraphs beginning The first chip is Ascend 950PR; With HiBL 1.0; This chip will be available';$lT='H-2 paragraphs beginning The next chip is Ascend 950DT; These two scenarios; The Ascend 950DT chip will be available';$l6='H-6 active Ascend 950PR body and feature cards';$l6n='H-6 processor navigation and DT route';$l12='H-12 paragraph beginning 同时，在峰会上宣布 and section 新品发布'
AA 'ASSERT-M2W3-HUAWEI-DIE-VENDOR-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-VENDOR' $H2 identity supports Huawei '' '' 'H-2 publisher/title' '' ''
AA 'ASSERT-M2W3-HUAWEI-DIE-FAMILY-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-FAMILY' $H2 identity supports 'Ascend 950 series' '' '' 'H-2: Over the next three years' '' ''
AA 'ASSERT-M2W3-HUAWEI-DIE-NAME-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-NAME' $H2 identity supports 'Ascend 950 Die' '' '' 'H-2: At the moment' '' ''
AA 'ASSERT-M2W3-HUAWEI-DIE-TYPE-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-OBJECT-TYPE' $H2 identity supports 'Ascend 950 Die' '' '' 'H-2: At the moment' '' 'Exact die term.'
AA 'ASSERT-M2W3-HUAWEI-DIE-RELEASE-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-RELEASE-DATE' $H2 status_version supports '2025-09-18' '' '' 'H-2 publication date' '' 'First public disclosure.'
foreach($x in @(@('FP8','1'),@('MXFP8','1'),@('HIF8','1'),@('MXFP4','2'))){AA "ASSERT-M2W3-HUAWEI-DIE-$($x[0])-H2" "FACT-M2W3-HUAWEI-ASC950-DIE-$($x[0])-THROUGHPUT" $H2 core_spec qualifies '' $x[1] PFLOPS $lS "Ascend 950 chips will deliver $($x[1]) PFLOPS in $($x[0])" 'Common-series subject stored once on shared die; operation semantics unresolved.'}
AA 'ASSERT-M2W3-HUAWEI-DIE-VECTOR-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-VECTOR-EXECUTION' $H2 architecture_mechanism qualifies 'innovative design that combines SIMD and SIMT' '' '' $lS '' 'Common-series subject stored once.'
AA 'ASSERT-M2W3-HUAWEI-DIE-GRAN-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-MEM-GRANULARITY' $H2 architecture_mechanism qualifies '' 128 byte $lS 'from 512 bytes to 128 bytes' 'No memory level named.'
AA 'ASSERT-M2W3-HUAWEI-DIE-LINK-H2' 'FACT-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT-BW' $H2 core_spec qualifies '' 2 'TB/s' $lS 'Ascend 950 chips will deliver 2 TB/s interconnect bandwidth' 'Direction unknown.'
AA 'ASSERT-M2W3-HUAWEI-PR-VENDOR-H2' 'FACT-M2W3-HUAWEI-ASC950PR-VENDOR' $H2 identity supports Huawei '' '' 'H-2 publisher/title' '' ''
AA 'ASSERT-M2W3-HUAWEI-PR-VENDOR-H6' 'FACT-M2W3-HUAWEI-ASC950PR-VENDOR' $H6 identity supports Huawei '' '' 'H-6 publisher/product page' '' ''
AA 'ASSERT-M2W3-HUAWEI-PR-FAMILY-H2' 'FACT-M2W3-HUAWEI-ASC950PR-FAMILY' $H2 identity supports 'Ascend 950 series includes Ascend 950PR' '' '' 'H-2: Over the next three years' '' ''
foreach($s in @($H2,$H6,$H12)){ $tag=if($s-eq$H2){'H2'}elseif($s-eq$H6){'H6'}else{'H12'};$loc=if($s-eq$H2){$lP}elseif($s-eq$H6){$l6}else{$l12};AA "ASSERT-M2W3-HUAWEI-PR-NAME-$tag" 'FACT-M2W3-HUAWEI-ASC950PR-NAME' $s identity supports 'Ascend 950PR' '' '' $loc '' '';AA "ASSERT-M2W3-HUAWEI-PR-SKU-$tag" 'FACT-M2W3-HUAWEI-ASC950PR-SKU' $s identity supports 'Ascend 950PR' '' '' $loc '' ''}
AA 'ASSERT-M2W3-HUAWEI-PR-TYPE-H2' 'FACT-M2W3-HUAWEI-ASC950PR-OBJECT-TYPE' $H2 identity qualifies 'HiBL 1.0 separately packaged with the Ascend 950 Die' '' '' $lP '' 'Formal package layer normalization.'
AA 'ASSERT-M2W3-HUAWEI-PR-RELEASE-H2' 'FACT-M2W3-HUAWEI-ASC950PR-RELEASE-DATE' $H2 status_version supports '2025-09-18' '' '' 'H-2 publication date' '' 'First disclosure.'
AA 'ASSERT-M2W3-HUAWEI-PR-STATUS-H2' 'FACT-M2W3-HUAWEI-ASC950PR-STATUS' $H2 status_version qualifies 'available in the first quarter of 2026' '' '' $lP '' 'Earlier roadmap, not actual standalone availability.'
AA 'ASSERT-M2W3-HUAWEI-PR-STATUS-H12' 'FACT-M2W3-HUAWEI-ASC950PR-STATUS' $H12 status_version supports '搭载昇腾950PR的Atlas 350加速卡正式上市' '' '' $l12 '' 'Embedded commercial use only.'
AA 'ASSERT-M2W3-HUAWEI-PR-POS-H2' 'FACT-M2W3-HUAWEI-ASC950PR-POSITIONING' $H2 identity supports 'prefill stage and recommendation systems' '' '' $lP '' ''
AA 'ASSERT-M2W3-HUAWEI-PR-POS-H6' 'FACT-M2W3-HUAWEI-ASC950PR-POSITIONING' $H6 identity supports '聚焦LLM Prefill阶段以及高性能推荐业务' '' '' $l6 '' ''
AA 'ASSERT-M2W3-HUAWEI-PR-DEPLOY-H12' 'FACT-M2W3-HUAWEI-ASC950PR-DEPLOYMENT' $H12 status_version supports 'Atlas 350正式上市；7家伙伴首发整机' '' '' $l12 '' 'No card value transferred.'
AA 'ASSERT-M2W3-HUAWEI-PR-PKG-H2' 'FACT-M2W3-HUAWEI-ASC950PR-PACKAGE' $H2 core_spec supports 'HiBL 1.0 separately packaged with the Ascend 950 Die' '' '' $lP '' ''
AA 'ASSERT-M2W3-HUAWEI-PR-MEMNAME-H2' 'FACT-M2W3-HUAWEI-ASC950PR-MEM-NAME' $H2 core_spec supports 'HiBL 1.0 proprietary HBM' '' '' $lP '' ''
AA 'ASSERT-M2W3-HUAWEI-PR-MEMCAP-H6' 'FACT-M2W3-HUAWEI-ASC950PR-MEM-CAPACITY' $H6 core_spec supports '' 128 GB $l6 '最大配备128GB' 'Package current value, not Atlas 350.'
AA 'ASSERT-M2W3-HUAWEI-PR-MEMBW-H6' 'FACT-M2W3-HUAWEI-ASC950PR-MEM-BW' $H6 core_spec supports '' 1.6 'TB/s' $l6 '1.6TB/s高速片上内存' 'Direction unknown.'
AA 'ASSERT-M2W3-HUAWEI-PR-PEAK-H6' 'FACT-M2W3-HUAWEI-ASC950PR-VENDOR-MAX-THROUGHPUT' $H6 core_spec qualifies '' 1784 TFLOPS $l6 '最大支持1784TFLOPS' 'Datatype/count unresolved.'
AA 'ASSERT-M2W3-HUAWEI-PR-PROTOCOL-H6' 'FACT-M2W3-HUAWEI-ASC950PR-INTERCONNECT-PROTOCOL' $H6 core_spec supports '灵衢2.0互联协议' '' '' $l6 '' ''
AA 'ASSERT-M2W3-HUAWEI-PR-LINK-H6' 'FACT-M2W3-HUAWEI-ASC950PR-INTERCONNECT-BW' $H6 core_spec supports '' 2 'TB/s' $l6 '最大支持2TB/s双向互联带宽' 'Explicit bidirectional aggregate.'
AA 'ASSERT-M2W3-HUAWEI-DT-VENDOR-H2' 'FACT-M2W3-HUAWEI-ASC950DT-VENDOR' $H2 identity supports Huawei '' '' 'H-2 publisher/title' '' ''
AA 'ASSERT-M2W3-HUAWEI-DT-FAMILY-H2' 'FACT-M2W3-HUAWEI-ASC950DT-FAMILY' $H2 identity supports 'Ascend 950 series includes Ascend 950DT' '' '' 'H-2: Over the next three years' '' ''
AA 'ASSERT-M2W3-HUAWEI-DT-NAME-H2' 'FACT-M2W3-HUAWEI-ASC950DT-NAME' $H2 identity supports 'Ascend 950DT' '' '' $lT '' ''
AA 'ASSERT-M2W3-HUAWEI-DT-NAME-H6' 'FACT-M2W3-HUAWEI-ASC950DT-NAME' $H6 identity qualifies 'Ascend 950DT' '' '' $l6n '' 'Route identity only; body remains PR.'
AA 'ASSERT-M2W3-HUAWEI-DT-SKU-H2' 'FACT-M2W3-HUAWEI-ASC950DT-SKU' $H2 identity supports 'Ascend 950DT' '' '' $lT '' ''
AA 'ASSERT-M2W3-HUAWEI-DT-SKU-H6' 'FACT-M2W3-HUAWEI-ASC950DT-SKU' $H6 identity qualifies 'Ascend 950DT' '' '' $l6n '' 'Route identity only; body remains PR.'
AA 'ASSERT-M2W3-HUAWEI-DT-TYPE-H2' 'FACT-M2W3-HUAWEI-ASC950DT-OBJECT-TYPE' $H2 identity qualifies 'HiZQ 2.0 separately packaged with the Ascend 950 Die' '' '' $lT '' 'Formal package layer normalization.'
AA 'ASSERT-M2W3-HUAWEI-DT-RELEASE-H2' 'FACT-M2W3-HUAWEI-ASC950DT-RELEASE-DATE' $H2 status_version supports '2025-09-18' '' '' 'H-2 publication date' '' 'First disclosure.'
AA 'ASSERT-M2W3-HUAWEI-DT-STATUS-H2' 'FACT-M2W3-HUAWEI-ASC950DT-STATUS' $H2 status_version qualifies 'available in the fourth quarter of 2026' '' '' $lT '' 'Future roadmap normalized to announced only.'
AA 'ASSERT-M2W3-HUAWEI-DT-POS-H2' 'FACT-M2W3-HUAWEI-ASC950DT-POSITIONING' $H2 identity supports 'decode stage and model training' '' '' $lT '' ''
AA 'ASSERT-M2W3-HUAWEI-DT-PKG-H2' 'FACT-M2W3-HUAWEI-ASC950DT-PACKAGE' $H2 core_spec supports 'HiZQ 2.0 separately packaged with the Ascend 950 Die' '' '' $lT '' ''
AA 'ASSERT-M2W3-HUAWEI-DT-MEMNAME-H2' 'FACT-M2W3-HUAWEI-ASC950DT-MEM-NAME' $H2 core_spec supports 'HiZQ 2.0 HBM' '' '' $lT '' 'Roadmap.'
AA 'ASSERT-M2W3-HUAWEI-DT-MEMCAP-H2' 'FACT-M2W3-HUAWEI-ASC950DT-MEM-CAPACITY' $H2 core_spec supports '' 144 GB $lT 'delivering 144 GB of memory' 'Roadmap.'
AA 'ASSERT-M2W3-HUAWEI-DT-MEMBW-H2' 'FACT-M2W3-HUAWEI-ASC950DT-MEM-BW' $H2 core_spec supports '' 4 'TB/s' $lT '4 TB/s memory access bandwidth' 'Direction unknown; roadmap.'
AA 'ASSERT-M2W3-HUAWEI-DT-LINK-H2' 'FACT-M2W3-HUAWEI-ASC950DT-INTERCONNECT-BW' $H2 core_spec supports '' 2 'TB/s' $lT 'total interconnect bandwidth will reach 2 TB/s' 'Direction unknown; roadmap.'
$inferredAssertionNotes=[ordered]@{
  'ASSERT-M2W3-HUAWEI-DIE-FP8-H2'='Common-series value; direct source subject is "Ascend 950 chips". Shared-die assignment is inferred from the preceding same-die statement; operation semantics unresolved.'
  'ASSERT-M2W3-HUAWEI-DIE-MXFP8-H2'='Common-series value; direct source subject is "Ascend 950 chips". Shared-die assignment is inferred from the preceding same-die statement; operation semantics unresolved.'
  'ASSERT-M2W3-HUAWEI-DIE-HIF8-H2'='Common-series value; direct source subject is "Ascend 950 chips". Shared-die assignment is inferred from the preceding same-die statement; operation semantics unresolved.'
  'ASSERT-M2W3-HUAWEI-DIE-MXFP4-H2'='Common-series value; direct source subject is "Ascend 950 chips". Shared-die assignment is inferred from the preceding same-die statement; operation semantics unresolved.'
  'ASSERT-M2W3-HUAWEI-DIE-VECTOR-H2'='Direct source subject is "Ascend 950 chips". Shared-die assignment is inferred from the preceding same-die statement.'
  'ASSERT-M2W3-HUAWEI-DIE-GRAN-H2'='Direct source subject is "Ascend 950 chips". Shared-die assignment is inferred from the preceding same-die statement; no memory level named.'
  'ASSERT-M2W3-HUAWEI-DIE-LINK-H2'='Direct source subject is "Ascend 950 chips". Shared-die assignment is inferred from the preceding same-die statement. This shared 2 TB/s, the DT-roadmap 2 TB/s and the current PR Lingqu 2.0 2 TB/s are condition-specific and not additive; direction unknown.'
  'ASSERT-M2W3-HUAWEI-PR-STATUS-H12'='H-12 directly launches Atlas 350 carrying 950PR. Mapping that statement to package status available is an inferred subject/status normalization limited to the embedded-product condition.'
}
foreach($assertionRow in $ass){if($inferredAssertionNotes.Contains($assertionRow.assertion_id)){$assertionRow.assertion_mode='inferred';$assertionRow.notes=$inferredAssertionNotes[$assertionRow.assertion_id]}}
foreach($f in $facts){$k='';$id='';foreach($x in @(@('object','object_id'),@('component','component_id'),@('link','link_id'),@('precision_path','precision_path_id'))){if($f.($x[1])){$k=$x[0];$id=$f.($x[1]);break}};$v=[ordered]@{requirement_id=($f.fact_id-replace'^FACT-','REQ-');field_id=$f.field_id;requirement_status='value_available';applicability_reason='Direct first-party value accepted with its condition and layer boundary.';search_status='completed';last_searched_date='2026-08-13';requirement_fingerprint="$k|$id|$($f.field_id)";review_status='draft';notes=$f.notes};$v[(@{object='object_id';component='component_id';link='link_id';precision_path='precision_path_id'}[$k])]=$id;$req.Add((NR '数据/field-requirements.csv' $v))}
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-STATUS' object $D 'FIELD-ID-STATUS' not_applicable 'Shared die is not a standalone product; status belongs to PR/DT packages.' ''
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-AVAILABILITY' object $D 'FIELD-ID-AVAILABILITY-DATE' not_applicable 'Shared die is not independently offered; availability belongs to package/product.' ''
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-SKU' object $D 'FIELD-ID-SKU' not_applicable 'Shared physical die is not a separately named commercial SKU.' ''
foreach($x in @(@('PROCESS','FIELD-PHY-PROCESS','Process node'),@('DIE-AREA','FIELD-PHY-DIE-AREA','Die area'),@('TRANSISTORS','FIELD-PHY-TRANSISTORS','Transistor count'),@('CLOCK','FIELD-PHY-CLOCK','Clock'),@('POWER','FIELD-PHY-POWER','Die power'))){AR "REQ-M2W3-HUAWEI-ASC950-DIE-$($x[0])" object $D $x[1] not_found "$($x[2]) absent from frozen official sources." 'No third-party estimate.'}
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-VECTOR-THROUGHPUT' object $D 'FIELD-COMP-THROUGHPUT' not_found 'H-2 says vector processing is stronger but gives no separately conditioned vector throughput.' 'No derivation from total labels.'
foreach($p0 in @('FP8','MXFP8','HIF8','MXFP4')){$ppid="PPATH-M2W3-HUAWEI-ASC950-DIE-$p0";AR "REQ-M2W3-HUAWEI-ASC950-DIE-$p0-ACCUM" precision_path $ppid 'FIELD-NUM-ACCUMULATION' not_found "$p0 programmer-visible accumulation format absent." 'Input label is not accumulation evidence.';AR "REQ-M2W3-HUAWEI-ASC950-DIE-$p0-PHYSICAL-ACCUM" precision_path $ppid 'FIELD-NUM-PHYSICAL-ACCUM' not_found "$p0 physical accumulator semantics absent." 'No inference.'}
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-MEMORY-NAME' object $D 'FIELD-MEM-NAME' not_found 'No complete on-die storage hierarchy or named cache/SRAM level.' 'HiBL/HiZQ are package memories.'
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-MEMORY-CAPACITY' object $D 'FIELD-MEM-CAPACITY' not_found 'No on-die storage capacity.' 'Package HBM excluded.'
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-MEMORY-BW' object $D 'FIELD-MEM-BIDIR-BW' not_found 'No on-die storage-level bandwidth.' '128-byte granularity is not bandwidth.'
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-LINK-RATE' link 'LINK-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT' 'FIELD-INT-PER-LINK-RATE' not_found 'Only aggregate interconnect label is given.' ''
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-LINK-COUNT' link 'LINK-M2W3-HUAWEI-ASC950-DIE-INTERCONNECT' 'FIELD-INT-LINK-COUNT' not_found 'No logical/physical link count.' ''
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-SPECIAL-DETAIL' object $D 'FIELD-CAP-IMPLEMENTATION-DETAIL' not_found 'No dedicated MoE routing, Top-k, attention, sampling or KV-cache block identified.' 'No capability placeholder.'
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-COMPILER' object $D 'FIELD-SW-COMPILER' not_found 'No exact die-matched compiler/version.' ''
AR 'REQ-M2W3-HUAWEI-ASC950-DIE-RUNTIME' object $D 'FIELD-SW-RUNTIME' not_found 'No exact die-matched runtime/version.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-AVAILABILITY' object $P 'FIELD-ID-AVAILABILITY-DATE' not_found 'H-2 gives Q1 2026 and H-12 dates Atlas 350, not exact standalone PR availability.' 'Embedded use recorded separately.'
foreach($x in @(@('PROCESS','FIELD-PHY-PROCESS'),@('DIE-AREA','FIELD-PHY-DIE-AREA'),@('TRANSISTORS','FIELD-PHY-TRANSISTORS'))){AR "REQ-M2W3-HUAWEI-ASC950PR-$($x[0])" object $P $x[1] not_applicable 'Attribute belongs to contained shared die and is not duplicated on PR package.' 'Use OREL-HUAWEI-950PR-CONTAINS-950-DIE.'}
foreach($x in @(@('DIE-COUNT','FIELD-PHY-DIE-COUNT','Die quantity'),@('HBM-STACKS','FIELD-PHY-HBM-STACKS','HBM stack count'),@('HBM-INTERFACE','FIELD-PHY-HBM-INTERFACE','HBM interface width'),@('INTERPOSER','FIELD-PHY-INTERPOSER','Interposer/substrate'),@('POWER','FIELD-PHY-POWER','Package power'))){AR "REQ-M2W3-HUAWEI-ASC950PR-$($x[0])" object $P $x[1] not_found "$($x[2]) absent for PR package." 'Atlas 350 values excluded.'}
AR 'REQ-M2W3-HUAWEI-ASC950PR-COOLING' object $P 'FIELD-PHY-COOLING' not_applicable 'Cooling in available material belongs to card/system, not package.' 'Atlas 350 passive cooling excluded.'
AR 'REQ-M2W3-HUAWEI-ASC950PR-MEM-LATENCY' component 'COMP-M2W3-HUAWEI-ASC950PR-HIBL1' 'FIELD-MEM-LATENCY' not_found 'No HiBL 1.0 latency.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-MEM-RW-MODEL' component 'COMP-M2W3-HUAWEI-ASC950PR-HIBL1' 'FIELD-MEM-READ-WRITE-MODEL' not_found '1.6 TB/s label does not state read/write/aggregate semantics.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-LINK-RATE' link 'LINK-M2W3-HUAWEI-ASC950PR-LINGQU2' 'FIELD-INT-PER-LINK-RATE' not_found 'Only maximum bidirectional aggregate is given.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-LINK-COUNT' link 'LINK-M2W3-HUAWEI-ASC950PR-LINGQU2' 'FIELD-INT-LINK-COUNT' not_found 'No PR link count.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-TOPOLOGY' object $P 'FIELD-INT-TOPOLOGY' not_found 'No PR package/device topology.' 'Atlas 350 card topology excluded.'
AR 'REQ-M2W3-HUAWEI-ASC950PR-SPECIAL-DETAIL' object $P 'FIELD-CAP-IMPLEMENTATION-DETAIL' not_found 'No dedicated MoE/Top-k/attention/sampling/KV block identified for PR.' 'No capability placeholder.'
AR 'REQ-M2W3-HUAWEI-ASC950PR-COMPILER' object $P 'FIELD-SW-COMPILER' not_found 'No exact PR compiler/version.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-RUNTIME' object $P 'FIELD-SW-RUNTIME' not_found 'No exact PR runtime/version.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-ACCUM' precision_path 'PPATH-M2W3-HUAWEI-ASC950PR-VENDOR-MAX' 'FIELD-NUM-ACCUMULATION' not_found '1784 TFLOPS label omits datatype and programmer-visible accumulation.' ''
AR 'REQ-M2W3-HUAWEI-ASC950PR-PHYSICAL-ACCUM' precision_path 'PPATH-M2W3-HUAWEI-ASC950PR-VENDOR-MAX' 'FIELD-NUM-PHYSICAL-ACCUM' not_found 'Physical accumulator behind 1784 TFLOPS is absent.' ''
AR 'REQ-M2W3-HUAWEI-ASC950DT-AVAILABILITY' object $T 'FIELD-ID-AVAILABILITY-DATE' pending_verification 'H-2 gives Q4 2026 roadmap; no exact GA/delivery by 2026-08-13.' 'Recheck on DT product body or delivery notice.'
$revid.Add((NR '最小参考资料库/requirement-evidence.csv' ([ordered]@{requirement_evidence_id='REVID-M2W3-HUAWEI-ASC950DT-AVAILABILITY-H2';requirement_id='REQ-M2W3-HUAWEI-ASC950DT-AVAILABILITY';source_id=$H2;evidence_relation='supports_pending';source_locator=$lT;quoted_context='The Ascend 950DT chip will be available in the fourth quarter of 2026.';reviewer='m2_w3_huawei_asc950_physical';review_date='2026-08-13';review_status='draft';notes='Future roadmap only; no GA/delivery upgrade.'})))
foreach($x in @(@('PROCESS','FIELD-PHY-PROCESS'),@('DIE-AREA','FIELD-PHY-DIE-AREA'),@('TRANSISTORS','FIELD-PHY-TRANSISTORS'))){AR "REQ-M2W3-HUAWEI-ASC950DT-$($x[0])" object $T $x[1] not_applicable 'Attribute belongs to contained shared die and is not duplicated on DT package.' 'Use OREL-HUAWEI-950DT-CONTAINS-950-DIE.'}
foreach($x in @(@('DIE-COUNT','FIELD-PHY-DIE-COUNT','Die quantity'),@('HBM-STACKS','FIELD-PHY-HBM-STACKS','HBM stack count'),@('HBM-INTERFACE','FIELD-PHY-HBM-INTERFACE','HBM interface width'),@('INTERPOSER','FIELD-PHY-INTERPOSER','Interposer/substrate'),@('POWER','FIELD-PHY-POWER','Package power'))){AR "REQ-M2W3-HUAWEI-ASC950DT-$($x[0])" object $T $x[1] not_found "$($x[2]) absent for DT package." 'No third-party/SuperPoD value.'}
AR 'REQ-M2W3-HUAWEI-ASC950DT-COOLING' object $T 'FIELD-PHY-COOLING' not_applicable 'Cooling belongs to future card/system, not package roadmap.' 'No SuperPoD value.'
AR 'REQ-M2W3-HUAWEI-ASC950DT-MEM-LATENCY' component 'COMP-M2W3-HUAWEI-ASC950DT-HIZQ2' 'FIELD-MEM-LATENCY' not_found 'No HiZQ 2.0 latency.' ''
AR 'REQ-M2W3-HUAWEI-ASC950DT-MEM-RW-MODEL' component 'COMP-M2W3-HUAWEI-ASC950DT-HIZQ2' 'FIELD-MEM-READ-WRITE-MODEL' not_found '4 TB/s label does not state read/write/aggregate semantics.' ''
AR 'REQ-M2W3-HUAWEI-ASC950DT-LINK-RATE' link 'LINK-M2W3-HUAWEI-ASC950DT-INTERCONNECT' 'FIELD-INT-PER-LINK-RATE' not_found 'Only total bandwidth is given.' ''
AR 'REQ-M2W3-HUAWEI-ASC950DT-LINK-COUNT' link 'LINK-M2W3-HUAWEI-ASC950DT-INTERCONNECT' 'FIELD-INT-LINK-COUNT' not_found 'No DT link count.' ''
AR 'REQ-M2W3-HUAWEI-ASC950DT-TOPOLOGY' object $T 'FIELD-INT-TOPOLOGY' not_found 'No DT package/device topology.' 'SuperPoD topology excluded.'
AR 'REQ-M2W3-HUAWEI-ASC950DT-SPECIAL-DETAIL' object $T 'FIELD-CAP-IMPLEMENTATION-DETAIL' not_found 'No dedicated MoE/Top-k/attention/sampling/KV block identified for DT.' 'No capability placeholder.'
AR 'REQ-M2W3-HUAWEI-ASC950DT-COMPILER' object $T 'FIELD-SW-COMPILER' not_found 'No exact DT compiler/version.' ''
AR 'REQ-M2W3-HUAWEI-ASC950DT-RUNTIME' object $T 'FIELD-SW-RUNTIME' not_found 'No exact DT runtime/version.' ''
AR 'REQ-M2W3-HUAWEI-ASC950DT-ACCUM' object $T 'FIELD-NUM-ACCUMULATION' not_found 'Roadmap formats do not disclose programmer-visible accumulation for DT.' 'Shared paths not duplicated.'
AR 'REQ-M2W3-HUAWEI-ASC950DT-PHYSICAL-ACCUM' object $T 'FIELD-NUM-PHYSICAL-ACCUM' not_found 'No DT physical accumulator semantics.' 'Shared paths not duplicated.'
$states=@{$D=@('partial','missing_public_data','partial','partial','missing_public_data','partial','missing_public_data','missing_public_data','complete');$P=@('partial','partial','partial','missing_public_data','partial','partial','missing_public_data','missing_public_data','complete');$T=@('partial','partial','partial','partial','partial','partial','missing_public_data','missing_public_data','partial')};$dom=@('identity','physical','compute','numerics','memory','interconnect','special_engines','software','evidence')
foreach($o in @($D,$P,$T)){$tag=if($o-eq$D){'DIE'}elseif($o-eq$P){'PR'}else{'DT'};for($i=0;$i-lt9;$i++){$n="$tag $($dom[$i]) assessed against H-2/H-6/H-7/H-12; scope and missing-data states preserved.";if($tag-eq'DT'-and$dom[$i]-eq'evidence'){$n='H-2 is the only DT body source; H-6 DT route renders PR body; no GA/delivery evidence.'};if($tag-eq'PR'-and$dom[$i]-eq'identity'){$n='Current exact identity and embedded commercial use; no standalone delivery or exact availability date.'};if($tag-eq'DIE'-and$dom[$i]-eq'identity'){$n='Shared die identity fixed; standalone SKU/status/availability not applicable.'};$cc.Add((NR '数据/card-completeness.csv' ([ordered]@{card_completeness_id="CC-M2W3-HUAWEI-ASC950-$tag-$($dom[$i].ToUpper())";object_id=$o;domain=$dom[$i];completeness_status=$states[$o][$i];assessed_date='2026-08-13';assessor='m2_w3_huawei_asc950_physical';review_status='draft';notes=$n})))}}
$fd=@(@('SFAM-M2W3-HUAWEI-H2-ASC950-KEYNOTE','Huawei Connect 2025 Ascend roadmap keynote','event_material_set','Huawei','https://www.huawei.com/en/news/2025/9/hc-xu-keynote-speech'),@('SFAM-M2W3-HUAWEI-H6-PROCESSOR','Ascend NPU processor page','dynamic_page_history','Huawei Ascend','https://www.hiascend.com/hardware/processor'),@('SFAM-M2W3-HUAWEI-H7-ACCELERATOR','Atlas accelerator card page','dynamic_page_history','Huawei Ascend','https://www.hiascend.com/hardware/accelerator-card'),@('SFAM-M2W3-HUAWEI-H12-ATLAS350-LAUNCH','Atlas 350 launch news','publication_versions','Huawei Ascend','https://www.hiascend.com/activities/dynamic-news/20260320-3'))
foreach($x in $fd){$fams.Add((NR '最小参考资料库/source-families.csv' ([ordered]@{source_family_id=$x[0];canonical_title=$x[1];family_kind=$x[2];publisher_or_organization=$x[3];persistent_work_id=$x[4];review_status='draft';notes='Fixed official content for this package.'})))}
$sd=@(@($H2,'SFAM-M2W3-HUAWEI-H2-ASC950-KEYNOTE','Groundbreaking SuperPoD Interconnect: Leading a New Paradigm for AI Infrastructure','Huawei','conference_talk','2025-09-18','published-2025-09-18; snapshot-2026-08-13','en','8bf0f453e143562c7b5f3ead61f54a35da6020689dbc20aede772da0d00d7499'),@($H6,'SFAM-M2W3-HUAWEI-H6-PROCESSOR','昇腾NPU处理器','Huawei Ascend','product_page','','snapshot-2026-08-13','zh','33f477a551103a772c6e7e8b1ca24f3d17af590088927e7cbf0005e5a0ba7102'),@($H7,'SFAM-M2W3-HUAWEI-H7-ACCELERATOR','Atlas 加速卡-昇腾社区','Huawei Ascend','product_page','','snapshot-2026-08-13','zh','3cfdeba7221d272ac307a3a2ca6404433804b9d6c7922677f56216bf24c4d978'),@($H12,'SFAM-M2W3-HUAWEI-H12-ATLAS350-LAUNCH','技术创新赋能千行万业 昇腾人工智能伙伴峰会2026圆满举办','Huawei Ascend','press_release','2026-03-20','published-2026-03-20; snapshot-2026-08-13','zh','bdf89863ce0321f24f6c42ebfebda09d62cfad3468ef953e1277f6bda240a9dd'))
foreach($x in $sd){$src.Add((NR '最小参考资料库/sources.csv' ([ordered]@{source_id=$x[0];source_family_id=$x[1];title=$x[2];author_or_organization=$x[3];source_type=$x[4];publication_date=$x[5];version_label=$x[6];language=$x[7];source_authority='first_party';source_status='current';content_fingerprint="sha256:$($x[8])";last_verified_date='2026-08-13';review_status='draft';notes='Object and layer role recorded in screening/selection tables.'})))}
$ed=@(@('END-M2W3-HUAWEI-H2-SNAPSHOT',$H2,'https://www.huawei.com/en/news/2025/9/hc-xu-keynote-speech','huawei-connect-2025-ascend-roadmap-2026-08-13.html','8bf0f453e143562c7b5f3ead61f54a35da6020689dbc20aede772da0d00d7499','true','132684 bytes'),@('END-M2W3-HUAWEI-H6-PR-SNAPSHOT',$H6,'https://www.hiascend.com/hardware/processor','hiascend-processor-2026-08-13.html','33f477a551103a772c6e7e8b1ca24f3d17af590088927e7cbf0005e5a0ba7102','true','155776 bytes; active body PR'),@('END-M2W3-HUAWEI-H6-DT-ROUTE-SNAPSHOT',$H6,'https://www.hiascend.com/hardware/processor?tag=950dt','hiascend-processor-950dt-2026-08-13.html','6bc823f2bf7328f8fa9838f6b7b7f6ee1cde23e9ccb8b41f0d9a4067e7706b07','false','155931 bytes; DT route but PR server body; no DT spec'),@('END-M2W3-HUAWEI-H7-SNAPSHOT',$H7,'https://www.hiascend.com/hardware/accelerator-card','hiascend-accelerator-card-2026-08-13.html','3cfdeba7221d272ac307a3a2ca6404433804b9d6c7922677f56216bf24c4d978','true','202198 bytes; card specs excluded'),@('END-M2W3-HUAWEI-H12-SNAPSHOT',$H12,'https://www.hiascend.com/activities/dynamic-news/20260320-3','hiascend-atlas350-launch-2026-08-13.html','bdf89863ce0321f24f6c42ebfebda09d62cfad3468ef953e1277f6bda240a9dd','true','146149 bytes'))
foreach($x in $ed){$ends.Add((NR '最小参考资料库/source-endpoints.csv' ([ordered]@{endpoint_id=$x[0];source_id=$x[1];endpoint_type='web_snapshot';url=$x[2];local_path="审计/子代理交接/m2_staging/M2-W3-HUAWEI-ASCEND950-PHYSICAL/fixed-candidates/$($x[3])";sha256=$x[4];mime_type='text/html';access_date='2026-08-13';http_status='200';snapshot_date='2026-08-13';is_preferred_endpoint=$x[5];accessibility_status='accessible';review_status='draft';notes=$x[6]})))}
foreach($x in @(@('SCREEN-M2W3-HUAWEI-H2',$H2,'selected','Unique shared-die, package split, common labels and DT roadmap evidence.','full_text_read'),@('SCREEN-M2W3-HUAWEI-H6',$H6,'selected','Unique current PR memory, unresolved compute maximum and Lingqu 2.0; DT renderer caveat.','relevant_sections_read'),@('SCREEN-M2W3-HUAWEI-H7',$H7,'redundant_covered','Relevant PR-card relationship covered by dated H-12; all card specifications out of scope.','relevant_sections_read'),@('SCREEN-M2W3-HUAWEI-H12',$H12,'selected','Unique dated PR embedded-commercial status update through Atlas 350.','full_text_read'))){$screen.Add((NR '最小参考资料库/source-screening.csv' ([ordered]@{screening_id=$x[0];source_id=$x[1];screening_status=$x[2];rationale=$x[3];full_text_read_status=$x[4];screened_by='m2_w3_huawei_asc950_physical';screened_date='2026-08-13';screening_fingerprint="$($x[1])|$($x[2])|ASC950|2026-08-13";review_status='draft';notes='Fact set fixed at 41 direct facts.'})))}
foreach($x in @(@('SROLE-H2-ID',$H2,'identity','Shared die and two package identities.'),@('SROLE-H2-CORE',$H2,'core_spec','Common labels, packaging and DT roadmap specs.'),@('SROLE-H2-STATUS',$H2,'status_version_evidence','Q1 PR and Q4 DT roadmap windows.'),@('SROLE-H6-ID',$H6,'identity','Current PR body and DT route identity.'),@('SROLE-H6-CORE',$H6,'core_spec','Current PR memory, unresolved maximum and Lingqu.'),@('SROLE-H12-STATUS',$H12,'status_version_evidence','Dated Atlas 350 launch carrying PR.'))){$roles.Add((NR '最小参考资料库/source-selected-roles.csv' ([ordered]@{source_selected_role_id="M2W3-HUAWEI-$($x[0])";source_id=$x[1];selected_role=$x[2];rationale=$x[3];review_status='draft';notes='Three-object physical scope only.'})))}
$cov.Add((NR '最小参考资料库/source-coverage.csv' ([ordered]@{coverage_id='COV-M2W3-HUAWEI-H7-BY-H12';covered_source_id=$H7;covering_source_id=$H12;coverage_scope='selected_fact_set';equivalence_status='fully_covered';rationale='H-12 repeats the Atlas 350 carries PR relation and adds date/status; H-7 card values are out of scope.';reviewed_by='m2_w3_huawei_asc950_physical';review_date='2026-08-13';review_status='draft';notes='H-7 preserved for boundary audit, removed from minimum set.'})))
$rId='SELRUN-M2W3-HUAWEI-ASC950-PHYSICAL-20260813';$runs.Add((NR '最小参考资料库/selection-runs.csv' ([ordered]@{selection_run_id=$rId;scope_kind='custom';scope_id='M2-W3-HUAWEI-ASCEND950-PHYSICAL';cutoff_date='2026-08-13';algorithm_version='reverse-removal-v1+layer-adversarial-check';created_date='2026-08-13';reviewer='m2_w3_huawei_asc950_physical';status='draft';review_status='draft';notes='41 direct facts; zero Atlas-card, Da Vinci-backlog or third-party migration.'})))
foreach($x in @(@('H2',$H2,'core_spec','Removal loses shared die/common labels, package split, DT specs/status.'),@('H6',$H6,'core_spec','Removal loses current PR exact specs and route audit.'),@('H12',$H12,'status_version_evidence','Removal loses dated PR embedded commercial update.'))){$members.Add((NR '最小参考资料库/selection-members.csv' ([ordered]@{selection_member_id="SELMEM-M2W3-HUAWEI-$($x[0])";selection_run_id=$rId;source_id=$x[1];selected_role=$x[2];mandatory_reason=$x[3];review_status='draft';notes='Independent review pending.'})))}
WT '数据/card-completeness.csv' $cc.ToArray();WT '数据/components.csv' $comps.ToArray();WT '数据/condition-sets.csv' $conds.ToArray();WT '数据/derived-inputs.csv' @();WT '数据/derived-metrics.csv' @();WT '最小参考资料库/fact-assertions.csv' $ass.ToArray();WT '数据/facts.csv' $facts.ToArray();WT '数据/field-requirements.csv' $req.ToArray();WT '数据/links.csv' $links.ToArray();WT '数据/memory-levels.csv' $mem.ToArray();WT '数据/precision-paths.csv' $pps.ToArray();WT '最小参考资料库/requirement-evidence.csv' $revid.ToArray();WT '最小参考资料库/search-log.csv' $logs.ToArray();WT '最小参考资料库/search-results.csv' $results.ToArray();WT '最小参考资料库/selection-members.csv' $members.ToArray();WT '最小参考资料库/selection-runs.csv' $runs.ToArray();WT '最小参考资料库/source-coverage.csv' $cov.ToArray();WT '最小参考资料库/source-endpoints.csv' $ends.ToArray();WT '最小参考资料库/source-families.csv' $fams.ToArray();WT '最小参考资料库/source-screening.csv' $screen.ToArray();WT '最小参考资料库/source-selected-roles.csv' $roles.ToArray();WT '最小参考资料库/sources.csv' $src.ToArray();WT '数据/special-capabilities.csv' @();WT '数据/topologies.csv' @()
[pscustomobject]@{facts=$facts.Count;assertions=$ass.Count;requirements=$req.Count;value_available=@($req|? requirement_status -eq value_available).Count;not_found=@($req|? requirement_status -eq not_found).Count;not_applicable=@($req|? requirement_status -eq not_applicable).Count;pending=@($req|? requirement_status -eq pending_verification).Count;components=$comps.Count;memory=$mem.Count;links=$links.Count;precision=$pps.Count;conditions=$conds.Count;completeness=$cc.Count;sources=$src.Count;endpoints=$ends.Count;search_logs=$logs.Count;search_results=$results.Count}|ConvertTo-Json